// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/protobuf/eager_service.proto

package core_protos_go_proto // import "github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import attr_value_go_proto "github.com/tensorflow/tensorflow/tensorflow/go/core/framework/attr_value_go_proto"
import device_attributes_go_proto "github.com/tensorflow/tensorflow/tensorflow/go/core/framework/device_attributes_go_proto"
import function_go_proto "github.com/tensorflow/tensorflow/tensorflow/go/core/framework/function_go_proto"
import tensor_go_proto "github.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor_go_proto"
import tensor_shape_go_proto "github.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor_shape_go_proto"
import versions_go_proto "github.com/tensorflow/tensorflow/tensorflow/go/core/framework/versions_go_proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A proto representation of an eager operation.
type Operation struct {
	// A unique identifier for the operation. Set by the client so that the client
	// can uniquely identify the outputs of the scheduled operation.
	//
	// In the initial implementation, sending duplicate IDs has undefined
	// behaviour, but additional constraints may be placed upon this in the
	// future.
	Id       int64              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OpInputs []*Operation_Input `protobuf:"bytes,10,rep,name=op_inputs,json=opInputs,proto3" json:"op_inputs,omitempty"`
	// Control Operation IDs that will be respected when ops are re-ordered by
	// async execution. If async execution (+ op re-ordering) is not enabled, this
	// should have no effect.
	ControlOpIds []int64                                   `protobuf:"varint,4,rep,packed,name=control_op_ids,json=controlOpIds,proto3" json:"control_op_ids,omitempty"`
	Attrs        map[string]*attr_value_go_proto.AttrValue `protobuf:"bytes,5,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Device       string                                    `protobuf:"bytes,6,opt,name=device,proto3" json:"device,omitempty"`
	// Indicates whether the op is a component of a multi-device function.
	IsComponentFunction bool `protobuf:"varint,7,opt,name=is_component_function,json=isComponentFunction,proto3" json:"is_component_function,omitempty"`
	// Set when is_component_function is true. It's initially generated
	// when we create an FunctionLibraryRuntime::Options (negative value) and used
	// to create Rendezvous for function execution. All components of a
	// multi-device function should use the same step id to make sure that they
	// can communicate through Send/Recv ops.
	FuncStepId int64 `protobuf:"varint,8,opt,name=func_step_id,json=funcStepId,proto3" json:"func_step_id,omitempty"`
	// Indicates whether the op is a function.
	IsFunction           bool     `protobuf:"varint,9,opt,name=is_function,json=isFunction,proto3" json:"is_function,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{0}
}
func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (dst *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(dst, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Operation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Operation) GetOpInputs() []*Operation_Input {
	if m != nil {
		return m.OpInputs
	}
	return nil
}

func (m *Operation) GetControlOpIds() []int64 {
	if m != nil {
		return m.ControlOpIds
	}
	return nil
}

func (m *Operation) GetAttrs() map[string]*attr_value_go_proto.AttrValue {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (m *Operation) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *Operation) GetIsComponentFunction() bool {
	if m != nil {
		return m.IsComponentFunction
	}
	return false
}

func (m *Operation) GetFuncStepId() int64 {
	if m != nil {
		return m.FuncStepId
	}
	return 0
}

func (m *Operation) GetIsFunction() bool {
	if m != nil {
		return m.IsFunction
	}
	return false
}

type Operation_Input struct {
	// Types that are valid to be assigned to Item:
	//	*Operation_Input_RemoteHandle
	//	*Operation_Input_Tensor
	Item                 isOperation_Input_Item `protobuf_oneof:"item"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Operation_Input) Reset()         { *m = Operation_Input{} }
func (m *Operation_Input) String() string { return proto.CompactTextString(m) }
func (*Operation_Input) ProtoMessage()    {}
func (*Operation_Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{0, 0}
}
func (m *Operation_Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation_Input.Unmarshal(m, b)
}
func (m *Operation_Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation_Input.Marshal(b, m, deterministic)
}
func (dst *Operation_Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation_Input.Merge(dst, src)
}
func (m *Operation_Input) XXX_Size() int {
	return xxx_messageInfo_Operation_Input.Size(m)
}
func (m *Operation_Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Operation_Input proto.InternalMessageInfo

type isOperation_Input_Item interface {
	isOperation_Input_Item()
}

type Operation_Input_RemoteHandle struct {
	RemoteHandle *RemoteTensorHandle `protobuf:"bytes,1,opt,name=remote_handle,json=remoteHandle,proto3,oneof"`
}

type Operation_Input_Tensor struct {
	Tensor *tensor_go_proto.TensorProto `protobuf:"bytes,2,opt,name=tensor,proto3,oneof"`
}

func (*Operation_Input_RemoteHandle) isOperation_Input_Item() {}

func (*Operation_Input_Tensor) isOperation_Input_Item() {}

func (m *Operation_Input) GetItem() isOperation_Input_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *Operation_Input) GetRemoteHandle() *RemoteTensorHandle {
	if x, ok := m.GetItem().(*Operation_Input_RemoteHandle); ok {
		return x.RemoteHandle
	}
	return nil
}

func (m *Operation_Input) GetTensor() *tensor_go_proto.TensorProto {
	if x, ok := m.GetItem().(*Operation_Input_Tensor); ok {
		return x.Tensor
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Operation_Input) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Operation_Input_OneofMarshaler, _Operation_Input_OneofUnmarshaler, _Operation_Input_OneofSizer, []interface{}{
		(*Operation_Input_RemoteHandle)(nil),
		(*Operation_Input_Tensor)(nil),
	}
}

func _Operation_Input_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Operation_Input)
	// item
	switch x := m.Item.(type) {
	case *Operation_Input_RemoteHandle:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RemoteHandle); err != nil {
			return err
		}
	case *Operation_Input_Tensor:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Tensor); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Operation_Input.Item has unexpected type %T", x)
	}
	return nil
}

func _Operation_Input_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Operation_Input)
	switch tag {
	case 1: // item.remote_handle
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RemoteTensorHandle)
		err := b.DecodeMessage(msg)
		m.Item = &Operation_Input_RemoteHandle{msg}
		return true, err
	case 2: // item.tensor
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(tensor_go_proto.TensorProto)
		err := b.DecodeMessage(msg)
		m.Item = &Operation_Input_Tensor{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Operation_Input_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Operation_Input)
	// item
	switch x := m.Item.(type) {
	case *Operation_Input_RemoteHandle:
		s := proto.Size(x.RemoteHandle)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Operation_Input_Tensor:
		s := proto.Size(x.Tensor)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type QueueItem struct {
	// The remote executor should be able to handle either executing ops directly,
	// or releasing any unused tensor handles, since the tensor lifetime is
	// maintained by the client.
	//
	// Types that are valid to be assigned to Item:
	//	*QueueItem_HandleToDecref
	//	*QueueItem_Operation
	//	*QueueItem_SendTensor
	//	*QueueItem_RegisterFunction
	//	*QueueItem_CleanupFunction
	//	*QueueItem_SyncRemoteExecutorForStream
	//	*QueueItem_SendPackedHandle
	Item                 isQueueItem_Item `protobuf_oneof:"item"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *QueueItem) Reset()         { *m = QueueItem{} }
func (m *QueueItem) String() string { return proto.CompactTextString(m) }
func (*QueueItem) ProtoMessage()    {}
func (*QueueItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{1}
}
func (m *QueueItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueItem.Unmarshal(m, b)
}
func (m *QueueItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueItem.Marshal(b, m, deterministic)
}
func (dst *QueueItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueItem.Merge(dst, src)
}
func (m *QueueItem) XXX_Size() int {
	return xxx_messageInfo_QueueItem.Size(m)
}
func (m *QueueItem) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueItem.DiscardUnknown(m)
}

var xxx_messageInfo_QueueItem proto.InternalMessageInfo

type isQueueItem_Item interface {
	isQueueItem_Item()
}

type QueueItem_HandleToDecref struct {
	HandleToDecref *RemoteTensorHandle `protobuf:"bytes,1,opt,name=handle_to_decref,json=handleToDecref,proto3,oneof"`
}

type QueueItem_Operation struct {
	Operation *Operation `protobuf:"bytes,2,opt,name=operation,proto3,oneof"`
}

type QueueItem_SendTensor struct {
	SendTensor *SendTensorOp `protobuf:"bytes,3,opt,name=send_tensor,json=sendTensor,proto3,oneof"`
}

type QueueItem_RegisterFunction struct {
	RegisterFunction *RegisterFunctionOp `protobuf:"bytes,4,opt,name=register_function,json=registerFunction,proto3,oneof"`
}

type QueueItem_CleanupFunction struct {
	CleanupFunction *CleanupFunctionOp `protobuf:"bytes,5,opt,name=cleanup_function,json=cleanupFunction,proto3,oneof"`
}

type QueueItem_SyncRemoteExecutorForStream struct {
	SyncRemoteExecutorForStream *SyncRemoteExecutorForStream `protobuf:"bytes,6,opt,name=sync_remote_executor_for_stream,json=syncRemoteExecutorForStream,proto3,oneof"`
}

type QueueItem_SendPackedHandle struct {
	SendPackedHandle *SendPackedHandleOp `protobuf:"bytes,7,opt,name=send_packed_handle,json=sendPackedHandle,proto3,oneof"`
}

func (*QueueItem_HandleToDecref) isQueueItem_Item() {}

func (*QueueItem_Operation) isQueueItem_Item() {}

func (*QueueItem_SendTensor) isQueueItem_Item() {}

func (*QueueItem_RegisterFunction) isQueueItem_Item() {}

func (*QueueItem_CleanupFunction) isQueueItem_Item() {}

func (*QueueItem_SyncRemoteExecutorForStream) isQueueItem_Item() {}

func (*QueueItem_SendPackedHandle) isQueueItem_Item() {}

func (m *QueueItem) GetItem() isQueueItem_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *QueueItem) GetHandleToDecref() *RemoteTensorHandle {
	if x, ok := m.GetItem().(*QueueItem_HandleToDecref); ok {
		return x.HandleToDecref
	}
	return nil
}

func (m *QueueItem) GetOperation() *Operation {
	if x, ok := m.GetItem().(*QueueItem_Operation); ok {
		return x.Operation
	}
	return nil
}

func (m *QueueItem) GetSendTensor() *SendTensorOp {
	if x, ok := m.GetItem().(*QueueItem_SendTensor); ok {
		return x.SendTensor
	}
	return nil
}

func (m *QueueItem) GetRegisterFunction() *RegisterFunctionOp {
	if x, ok := m.GetItem().(*QueueItem_RegisterFunction); ok {
		return x.RegisterFunction
	}
	return nil
}

func (m *QueueItem) GetCleanupFunction() *CleanupFunctionOp {
	if x, ok := m.GetItem().(*QueueItem_CleanupFunction); ok {
		return x.CleanupFunction
	}
	return nil
}

func (m *QueueItem) GetSyncRemoteExecutorForStream() *SyncRemoteExecutorForStream {
	if x, ok := m.GetItem().(*QueueItem_SyncRemoteExecutorForStream); ok {
		return x.SyncRemoteExecutorForStream
	}
	return nil
}

func (m *QueueItem) GetSendPackedHandle() *SendPackedHandleOp {
	if x, ok := m.GetItem().(*QueueItem_SendPackedHandle); ok {
		return x.SendPackedHandle
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*QueueItem) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _QueueItem_OneofMarshaler, _QueueItem_OneofUnmarshaler, _QueueItem_OneofSizer, []interface{}{
		(*QueueItem_HandleToDecref)(nil),
		(*QueueItem_Operation)(nil),
		(*QueueItem_SendTensor)(nil),
		(*QueueItem_RegisterFunction)(nil),
		(*QueueItem_CleanupFunction)(nil),
		(*QueueItem_SyncRemoteExecutorForStream)(nil),
		(*QueueItem_SendPackedHandle)(nil),
	}
}

func _QueueItem_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*QueueItem)
	// item
	switch x := m.Item.(type) {
	case *QueueItem_HandleToDecref:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HandleToDecref); err != nil {
			return err
		}
	case *QueueItem_Operation:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Operation); err != nil {
			return err
		}
	case *QueueItem_SendTensor:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SendTensor); err != nil {
			return err
		}
	case *QueueItem_RegisterFunction:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RegisterFunction); err != nil {
			return err
		}
	case *QueueItem_CleanupFunction:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CleanupFunction); err != nil {
			return err
		}
	case *QueueItem_SyncRemoteExecutorForStream:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SyncRemoteExecutorForStream); err != nil {
			return err
		}
	case *QueueItem_SendPackedHandle:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SendPackedHandle); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("QueueItem.Item has unexpected type %T", x)
	}
	return nil
}

func _QueueItem_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*QueueItem)
	switch tag {
	case 1: // item.handle_to_decref
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RemoteTensorHandle)
		err := b.DecodeMessage(msg)
		m.Item = &QueueItem_HandleToDecref{msg}
		return true, err
	case 2: // item.operation
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Operation)
		err := b.DecodeMessage(msg)
		m.Item = &QueueItem_Operation{msg}
		return true, err
	case 3: // item.send_tensor
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SendTensorOp)
		err := b.DecodeMessage(msg)
		m.Item = &QueueItem_SendTensor{msg}
		return true, err
	case 4: // item.register_function
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RegisterFunctionOp)
		err := b.DecodeMessage(msg)
		m.Item = &QueueItem_RegisterFunction{msg}
		return true, err
	case 5: // item.cleanup_function
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CleanupFunctionOp)
		err := b.DecodeMessage(msg)
		m.Item = &QueueItem_CleanupFunction{msg}
		return true, err
	case 6: // item.sync_remote_executor_for_stream
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SyncRemoteExecutorForStream)
		err := b.DecodeMessage(msg)
		m.Item = &QueueItem_SyncRemoteExecutorForStream{msg}
		return true, err
	case 7: // item.send_packed_handle
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SendPackedHandleOp)
		err := b.DecodeMessage(msg)
		m.Item = &QueueItem_SendPackedHandle{msg}
		return true, err
	default:
		return false, nil
	}
}

func _QueueItem_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*QueueItem)
	// item
	switch x := m.Item.(type) {
	case *QueueItem_HandleToDecref:
		s := proto.Size(x.HandleToDecref)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *QueueItem_Operation:
		s := proto.Size(x.Operation)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *QueueItem_SendTensor:
		s := proto.Size(x.SendTensor)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *QueueItem_RegisterFunction:
		s := proto.Size(x.RegisterFunction)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *QueueItem_CleanupFunction:
		s := proto.Size(x.CleanupFunction)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *QueueItem_SyncRemoteExecutorForStream:
		s := proto.Size(x.SyncRemoteExecutorForStream)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *QueueItem_SendPackedHandle:
		s := proto.Size(x.SendPackedHandle)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type QueueResponse struct {
	// `shape` and `tensor` cannot be set in the same response.
	// Shapes of output tensors for creating remote TensorHandles.
	Shape []*tensor_shape_go_proto.TensorShapeProto `protobuf:"bytes,1,rep,name=shape,proto3" json:"shape,omitempty"`
	// Output tensors of a remote function. Set when Operation.id is invalid.
	Tensor               []*tensor_go_proto.TensorProto `protobuf:"bytes,2,rep,name=tensor,proto3" json:"tensor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *QueueResponse) Reset()         { *m = QueueResponse{} }
func (m *QueueResponse) String() string { return proto.CompactTextString(m) }
func (*QueueResponse) ProtoMessage()    {}
func (*QueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{2}
}
func (m *QueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueResponse.Unmarshal(m, b)
}
func (m *QueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueResponse.Marshal(b, m, deterministic)
}
func (dst *QueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueResponse.Merge(dst, src)
}
func (m *QueueResponse) XXX_Size() int {
	return xxx_messageInfo_QueueResponse.Size(m)
}
func (m *QueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueueResponse proto.InternalMessageInfo

func (m *QueueResponse) GetShape() []*tensor_shape_go_proto.TensorShapeProto {
	if m != nil {
		return m.Shape
	}
	return nil
}

func (m *QueueResponse) GetTensor() []*tensor_go_proto.TensorProto {
	if m != nil {
		return m.Tensor
	}
	return nil
}

type CreateContextRequest struct {
	// Identifies the full cluster, and this particular worker's position within.
	ServerDef *ServerDef `protobuf:"bytes,1,opt,name=server_def,json=serverDef,proto3" json:"server_def,omitempty"`
	// Whether the ops on the worker should be executed synchronously or
	// asynchronously. By default, ops are executed synchronously.
	Async bool `protobuf:"varint,2,opt,name=async,proto3" json:"async,omitempty"`
	// Number of seconds to keep the context alive. If more than keep_alive_secs
	// has passed since a particular context has been communicated with, it will
	// be garbage collected.
	KeepAliveSecs int64 `protobuf:"varint,3,opt,name=keep_alive_secs,json=keepAliveSecs,proto3" json:"keep_alive_secs,omitempty"`
	// This is the version for all the ops that will be enqueued by the client.
	VersionDef *versions_go_proto.VersionDef `protobuf:"bytes,4,opt,name=version_def,json=versionDef,proto3" json:"version_def,omitempty"`
	// Device attributes in the cluster
	ClusterDeviceAttributes []*device_attributes_go_proto.DeviceAttributes `protobuf:"bytes,6,rep,name=cluster_device_attributes,json=clusterDeviceAttributes,proto3" json:"cluster_device_attributes,omitempty"`
	// The ID of the created context. This is usually a randomly generated number,
	// that will be used to identify the context in future requests to the
	// service. Contexts are not persisted through server restarts.
	// This ID will be used for all future communications as well. It is essential
	// that both ends use this ID for selecting a rendezvous to get everything to
	// match.
	ContextId uint64 `protobuf:"fixed64,7,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	// The view ID of the context.
	ContextViewId uint64 `protobuf:"fixed64,8,opt,name=context_view_id,json=contextViewId,proto3" json:"context_view_id,omitempty"`
	// For a multi device function, if false, eagerly copy all remote inputs to
	// the default function device; if true, lazily copy remote inputs to their
	// target devices after function instantiation to avoid redundant copies.
	LazyCopyRemoteFunctionInputs bool     `protobuf:"varint,9,opt,name=lazy_copy_remote_function_inputs,json=lazyCopyRemoteFunctionInputs,proto3" json:"lazy_copy_remote_function_inputs,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *CreateContextRequest) Reset()         { *m = CreateContextRequest{} }
func (m *CreateContextRequest) String() string { return proto.CompactTextString(m) }
func (*CreateContextRequest) ProtoMessage()    {}
func (*CreateContextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{3}
}
func (m *CreateContextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContextRequest.Unmarshal(m, b)
}
func (m *CreateContextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContextRequest.Marshal(b, m, deterministic)
}
func (dst *CreateContextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContextRequest.Merge(dst, src)
}
func (m *CreateContextRequest) XXX_Size() int {
	return xxx_messageInfo_CreateContextRequest.Size(m)
}
func (m *CreateContextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContextRequest proto.InternalMessageInfo

func (m *CreateContextRequest) GetServerDef() *ServerDef {
	if m != nil {
		return m.ServerDef
	}
	return nil
}

func (m *CreateContextRequest) GetAsync() bool {
	if m != nil {
		return m.Async
	}
	return false
}

func (m *CreateContextRequest) GetKeepAliveSecs() int64 {
	if m != nil {
		return m.KeepAliveSecs
	}
	return 0
}

func (m *CreateContextRequest) GetVersionDef() *versions_go_proto.VersionDef {
	if m != nil {
		return m.VersionDef
	}
	return nil
}

func (m *CreateContextRequest) GetClusterDeviceAttributes() []*device_attributes_go_proto.DeviceAttributes {
	if m != nil {
		return m.ClusterDeviceAttributes
	}
	return nil
}

func (m *CreateContextRequest) GetContextId() uint64 {
	if m != nil {
		return m.ContextId
	}
	return 0
}

func (m *CreateContextRequest) GetContextViewId() uint64 {
	if m != nil {
		return m.ContextViewId
	}
	return 0
}

func (m *CreateContextRequest) GetLazyCopyRemoteFunctionInputs() bool {
	if m != nil {
		return m.LazyCopyRemoteFunctionInputs
	}
	return false
}

type CreateContextResponse struct {
	// List of devices that are locally accessible to the worker.
	DeviceAttributes     []*device_attributes_go_proto.DeviceAttributes `protobuf:"bytes,2,rep,name=device_attributes,json=deviceAttributes,proto3" json:"device_attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *CreateContextResponse) Reset()         { *m = CreateContextResponse{} }
func (m *CreateContextResponse) String() string { return proto.CompactTextString(m) }
func (*CreateContextResponse) ProtoMessage()    {}
func (*CreateContextResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{4}
}
func (m *CreateContextResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContextResponse.Unmarshal(m, b)
}
func (m *CreateContextResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContextResponse.Marshal(b, m, deterministic)
}
func (dst *CreateContextResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContextResponse.Merge(dst, src)
}
func (m *CreateContextResponse) XXX_Size() int {
	return xxx_messageInfo_CreateContextResponse.Size(m)
}
func (m *CreateContextResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContextResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContextResponse proto.InternalMessageInfo

func (m *CreateContextResponse) GetDeviceAttributes() []*device_attributes_go_proto.DeviceAttributes {
	if m != nil {
		return m.DeviceAttributes
	}
	return nil
}

type UpdateContextRequest struct {
	// Identifies the full cluster, and this particular worker's position within.
	ServerDef *ServerDef `protobuf:"bytes,1,opt,name=server_def,json=serverDef,proto3" json:"server_def,omitempty"`
	// Device attributes in the cluster.
	// If this field is empty, it indicates that this is a simple update request
	// that only increments the cluster view ID and does not require changes to
	// the workers it connects to.
	ClusterDeviceAttributes []*device_attributes_go_proto.DeviceAttributes `protobuf:"bytes,2,rep,name=cluster_device_attributes,json=clusterDeviceAttributes,proto3" json:"cluster_device_attributes,omitempty"`
	// The ID of the context to be updated. A context with the specified ID must
	// already exist on the recepient server of this request.
	ContextId uint64 `protobuf:"fixed64,3,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	// The view ID of the context, which should be contiguously incremented when
	// updating the same context.
	ContextViewId        uint64   `protobuf:"fixed64,4,opt,name=context_view_id,json=contextViewId,proto3" json:"context_view_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateContextRequest) Reset()         { *m = UpdateContextRequest{} }
func (m *UpdateContextRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateContextRequest) ProtoMessage()    {}
func (*UpdateContextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{5}
}
func (m *UpdateContextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateContextRequest.Unmarshal(m, b)
}
func (m *UpdateContextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateContextRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateContextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateContextRequest.Merge(dst, src)
}
func (m *UpdateContextRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateContextRequest.Size(m)
}
func (m *UpdateContextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateContextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateContextRequest proto.InternalMessageInfo

func (m *UpdateContextRequest) GetServerDef() *ServerDef {
	if m != nil {
		return m.ServerDef
	}
	return nil
}

func (m *UpdateContextRequest) GetClusterDeviceAttributes() []*device_attributes_go_proto.DeviceAttributes {
	if m != nil {
		return m.ClusterDeviceAttributes
	}
	return nil
}

func (m *UpdateContextRequest) GetContextId() uint64 {
	if m != nil {
		return m.ContextId
	}
	return 0
}

func (m *UpdateContextRequest) GetContextViewId() uint64 {
	if m != nil {
		return m.ContextViewId
	}
	return 0
}

type UpdateContextResponse struct {
	// List of devices that are locally accessible to the worker.
	DeviceAttributes     []*device_attributes_go_proto.DeviceAttributes `protobuf:"bytes,1,rep,name=device_attributes,json=deviceAttributes,proto3" json:"device_attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *UpdateContextResponse) Reset()         { *m = UpdateContextResponse{} }
func (m *UpdateContextResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateContextResponse) ProtoMessage()    {}
func (*UpdateContextResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{6}
}
func (m *UpdateContextResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateContextResponse.Unmarshal(m, b)
}
func (m *UpdateContextResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateContextResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateContextResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateContextResponse.Merge(dst, src)
}
func (m *UpdateContextResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateContextResponse.Size(m)
}
func (m *UpdateContextResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateContextResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateContextResponse proto.InternalMessageInfo

func (m *UpdateContextResponse) GetDeviceAttributes() []*device_attributes_go_proto.DeviceAttributes {
	if m != nil {
		return m.DeviceAttributes
	}
	return nil
}

type EnqueueRequest struct {
	ContextId            uint64       `protobuf:"fixed64,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	Queue                []*QueueItem `protobuf:"bytes,3,rep,name=queue,proto3" json:"queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EnqueueRequest) Reset()         { *m = EnqueueRequest{} }
func (m *EnqueueRequest) String() string { return proto.CompactTextString(m) }
func (*EnqueueRequest) ProtoMessage()    {}
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{7}
}
func (m *EnqueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnqueueRequest.Unmarshal(m, b)
}
func (m *EnqueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnqueueRequest.Marshal(b, m, deterministic)
}
func (dst *EnqueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnqueueRequest.Merge(dst, src)
}
func (m *EnqueueRequest) XXX_Size() int {
	return xxx_messageInfo_EnqueueRequest.Size(m)
}
func (m *EnqueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnqueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnqueueRequest proto.InternalMessageInfo

func (m *EnqueueRequest) GetContextId() uint64 {
	if m != nil {
		return m.ContextId
	}
	return 0
}

func (m *EnqueueRequest) GetQueue() []*QueueItem {
	if m != nil {
		return m.Queue
	}
	return nil
}

type EnqueueResponse struct {
	// A single operation response for every item in the request.
	QueueResponse        []*QueueResponse `protobuf:"bytes,1,rep,name=queue_response,json=queueResponse,proto3" json:"queue_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EnqueueResponse) Reset()         { *m = EnqueueResponse{} }
func (m *EnqueueResponse) String() string { return proto.CompactTextString(m) }
func (*EnqueueResponse) ProtoMessage()    {}
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{8}
}
func (m *EnqueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnqueueResponse.Unmarshal(m, b)
}
func (m *EnqueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnqueueResponse.Marshal(b, m, deterministic)
}
func (dst *EnqueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnqueueResponse.Merge(dst, src)
}
func (m *EnqueueResponse) XXX_Size() int {
	return xxx_messageInfo_EnqueueResponse.Size(m)
}
func (m *EnqueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnqueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnqueueResponse proto.InternalMessageInfo

func (m *EnqueueResponse) GetQueueResponse() []*QueueResponse {
	if m != nil {
		return m.QueueResponse
	}
	return nil
}

type WaitQueueDoneRequest struct {
	ContextId uint64 `protobuf:"fixed64,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	// Ids to wait on. If empty, wait on everything currently pending.
	OpId                 []int64  `protobuf:"varint,2,rep,packed,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WaitQueueDoneRequest) Reset()         { *m = WaitQueueDoneRequest{} }
func (m *WaitQueueDoneRequest) String() string { return proto.CompactTextString(m) }
func (*WaitQueueDoneRequest) ProtoMessage()    {}
func (*WaitQueueDoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{9}
}
func (m *WaitQueueDoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaitQueueDoneRequest.Unmarshal(m, b)
}
func (m *WaitQueueDoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaitQueueDoneRequest.Marshal(b, m, deterministic)
}
func (dst *WaitQueueDoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaitQueueDoneRequest.Merge(dst, src)
}
func (m *WaitQueueDoneRequest) XXX_Size() int {
	return xxx_messageInfo_WaitQueueDoneRequest.Size(m)
}
func (m *WaitQueueDoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WaitQueueDoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WaitQueueDoneRequest proto.InternalMessageInfo

func (m *WaitQueueDoneRequest) GetContextId() uint64 {
	if m != nil {
		return m.ContextId
	}
	return 0
}

func (m *WaitQueueDoneRequest) GetOpId() []int64 {
	if m != nil {
		return m.OpId
	}
	return nil
}

type WaitQueueDoneResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WaitQueueDoneResponse) Reset()         { *m = WaitQueueDoneResponse{} }
func (m *WaitQueueDoneResponse) String() string { return proto.CompactTextString(m) }
func (*WaitQueueDoneResponse) ProtoMessage()    {}
func (*WaitQueueDoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{10}
}
func (m *WaitQueueDoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaitQueueDoneResponse.Unmarshal(m, b)
}
func (m *WaitQueueDoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaitQueueDoneResponse.Marshal(b, m, deterministic)
}
func (dst *WaitQueueDoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaitQueueDoneResponse.Merge(dst, src)
}
func (m *WaitQueueDoneResponse) XXX_Size() int {
	return xxx_messageInfo_WaitQueueDoneResponse.Size(m)
}
func (m *WaitQueueDoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WaitQueueDoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WaitQueueDoneResponse proto.InternalMessageInfo

type RunComponentFunctionRequest struct {
	ContextId            uint64     `protobuf:"fixed64,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	Operation            *Operation `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RunComponentFunctionRequest) Reset()         { *m = RunComponentFunctionRequest{} }
func (m *RunComponentFunctionRequest) String() string { return proto.CompactTextString(m) }
func (*RunComponentFunctionRequest) ProtoMessage()    {}
func (*RunComponentFunctionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{11}
}
func (m *RunComponentFunctionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunComponentFunctionRequest.Unmarshal(m, b)
}
func (m *RunComponentFunctionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunComponentFunctionRequest.Marshal(b, m, deterministic)
}
func (dst *RunComponentFunctionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunComponentFunctionRequest.Merge(dst, src)
}
func (m *RunComponentFunctionRequest) XXX_Size() int {
	return xxx_messageInfo_RunComponentFunctionRequest.Size(m)
}
func (m *RunComponentFunctionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunComponentFunctionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunComponentFunctionRequest proto.InternalMessageInfo

func (m *RunComponentFunctionRequest) GetContextId() uint64 {
	if m != nil {
		return m.ContextId
	}
	return 0
}

func (m *RunComponentFunctionRequest) GetOperation() *Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

type RunComponentFunctionResponse struct {
	Shape                []*tensor_shape_go_proto.TensorShapeProto `protobuf:"bytes,1,rep,name=shape,proto3" json:"shape,omitempty"`
	Tensor               []*tensor_go_proto.TensorProto            `protobuf:"bytes,2,rep,name=tensor,proto3" json:"tensor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *RunComponentFunctionResponse) Reset()         { *m = RunComponentFunctionResponse{} }
func (m *RunComponentFunctionResponse) String() string { return proto.CompactTextString(m) }
func (*RunComponentFunctionResponse) ProtoMessage()    {}
func (*RunComponentFunctionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{12}
}
func (m *RunComponentFunctionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunComponentFunctionResponse.Unmarshal(m, b)
}
func (m *RunComponentFunctionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunComponentFunctionResponse.Marshal(b, m, deterministic)
}
func (dst *RunComponentFunctionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunComponentFunctionResponse.Merge(dst, src)
}
func (m *RunComponentFunctionResponse) XXX_Size() int {
	return xxx_messageInfo_RunComponentFunctionResponse.Size(m)
}
func (m *RunComponentFunctionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunComponentFunctionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunComponentFunctionResponse proto.InternalMessageInfo

func (m *RunComponentFunctionResponse) GetShape() []*tensor_shape_go_proto.TensorShapeProto {
	if m != nil {
		return m.Shape
	}
	return nil
}

func (m *RunComponentFunctionResponse) GetTensor() []*tensor_go_proto.TensorProto {
	if m != nil {
		return m.Tensor
	}
	return nil
}

type KeepAliveRequest struct {
	ContextId            uint64   `protobuf:"fixed64,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepAliveRequest) Reset()         { *m = KeepAliveRequest{} }
func (m *KeepAliveRequest) String() string { return proto.CompactTextString(m) }
func (*KeepAliveRequest) ProtoMessage()    {}
func (*KeepAliveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{13}
}
func (m *KeepAliveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveRequest.Unmarshal(m, b)
}
func (m *KeepAliveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveRequest.Marshal(b, m, deterministic)
}
func (dst *KeepAliveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveRequest.Merge(dst, src)
}
func (m *KeepAliveRequest) XXX_Size() int {
	return xxx_messageInfo_KeepAliveRequest.Size(m)
}
func (m *KeepAliveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveRequest proto.InternalMessageInfo

func (m *KeepAliveRequest) GetContextId() uint64 {
	if m != nil {
		return m.ContextId
	}
	return 0
}

type KeepAliveResponse struct {
	// If the requested context_id is on the remote host, set the context view ID.
	ContextViewId        uint64   `protobuf:"fixed64,1,opt,name=context_view_id,json=contextViewId,proto3" json:"context_view_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepAliveResponse) Reset()         { *m = KeepAliveResponse{} }
func (m *KeepAliveResponse) String() string { return proto.CompactTextString(m) }
func (*KeepAliveResponse) ProtoMessage()    {}
func (*KeepAliveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{14}
}
func (m *KeepAliveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveResponse.Unmarshal(m, b)
}
func (m *KeepAliveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveResponse.Marshal(b, m, deterministic)
}
func (dst *KeepAliveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveResponse.Merge(dst, src)
}
func (m *KeepAliveResponse) XXX_Size() int {
	return xxx_messageInfo_KeepAliveResponse.Size(m)
}
func (m *KeepAliveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveResponse proto.InternalMessageInfo

func (m *KeepAliveResponse) GetContextViewId() uint64 {
	if m != nil {
		return m.ContextViewId
	}
	return 0
}

type CloseContextRequest struct {
	ContextId            uint64   `protobuf:"fixed64,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	ContextViewId        uint64   `protobuf:"fixed64,2,opt,name=context_view_id,json=contextViewId,proto3" json:"context_view_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseContextRequest) Reset()         { *m = CloseContextRequest{} }
func (m *CloseContextRequest) String() string { return proto.CompactTextString(m) }
func (*CloseContextRequest) ProtoMessage()    {}
func (*CloseContextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{15}
}
func (m *CloseContextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseContextRequest.Unmarshal(m, b)
}
func (m *CloseContextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseContextRequest.Marshal(b, m, deterministic)
}
func (dst *CloseContextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseContextRequest.Merge(dst, src)
}
func (m *CloseContextRequest) XXX_Size() int {
	return xxx_messageInfo_CloseContextRequest.Size(m)
}
func (m *CloseContextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseContextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseContextRequest proto.InternalMessageInfo

func (m *CloseContextRequest) GetContextId() uint64 {
	if m != nil {
		return m.ContextId
	}
	return 0
}

func (m *CloseContextRequest) GetContextViewId() uint64 {
	if m != nil {
		return m.ContextViewId
	}
	return 0
}

type CloseContextResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseContextResponse) Reset()         { *m = CloseContextResponse{} }
func (m *CloseContextResponse) String() string { return proto.CompactTextString(m) }
func (*CloseContextResponse) ProtoMessage()    {}
func (*CloseContextResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{16}
}
func (m *CloseContextResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseContextResponse.Unmarshal(m, b)
}
func (m *CloseContextResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseContextResponse.Marshal(b, m, deterministic)
}
func (dst *CloseContextResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseContextResponse.Merge(dst, src)
}
func (m *CloseContextResponse) XXX_Size() int {
	return xxx_messageInfo_CloseContextResponse.Size(m)
}
func (m *CloseContextResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseContextResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseContextResponse proto.InternalMessageInfo

type RegisterFunctionOp struct {
	FunctionDef *function_go_proto.FunctionDef `protobuf:"bytes,1,opt,name=function_def,json=functionDef,proto3" json:"function_def,omitempty"`
	// If true, it means that function_def is produced by graph partition during
	// multi-device function instantiation.
	IsComponentFunction bool `protobuf:"varint,2,opt,name=is_component_function,json=isComponentFunction,proto3" json:"is_component_function,omitempty"`
	// All necessary FunctionDefs and GradientDefs to expand `function_def`.
	// When is_component_function is true, `function_def` could be a nested
	// function, since some nodes in its parent's function body could be
	// replaced with a new function by the graph optimization passes. No need to
	// add FunctionDefs here to the function cache in EagerContext since they
	// won't be executed as KernelAndDevices.
	Library              *function_go_proto.FunctionDefLibrary `protobuf:"bytes,3,opt,name=library,proto3" json:"library,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *RegisterFunctionOp) Reset()         { *m = RegisterFunctionOp{} }
func (m *RegisterFunctionOp) String() string { return proto.CompactTextString(m) }
func (*RegisterFunctionOp) ProtoMessage()    {}
func (*RegisterFunctionOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{17}
}
func (m *RegisterFunctionOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterFunctionOp.Unmarshal(m, b)
}
func (m *RegisterFunctionOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterFunctionOp.Marshal(b, m, deterministic)
}
func (dst *RegisterFunctionOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterFunctionOp.Merge(dst, src)
}
func (m *RegisterFunctionOp) XXX_Size() int {
	return xxx_messageInfo_RegisterFunctionOp.Size(m)
}
func (m *RegisterFunctionOp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterFunctionOp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterFunctionOp proto.InternalMessageInfo

func (m *RegisterFunctionOp) GetFunctionDef() *function_go_proto.FunctionDef {
	if m != nil {
		return m.FunctionDef
	}
	return nil
}

func (m *RegisterFunctionOp) GetIsComponentFunction() bool {
	if m != nil {
		return m.IsComponentFunction
	}
	return false
}

func (m *RegisterFunctionOp) GetLibrary() *function_go_proto.FunctionDefLibrary {
	if m != nil {
		return m.Library
	}
	return nil
}

// Cleanup the step state of a multi-device function (e.g. tensors buffered by
// a `Send` op but not picked up by its corresponding `Recv` op).
type CleanupFunctionOp struct {
	StepId               int64    `protobuf:"varint,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CleanupFunctionOp) Reset()         { *m = CleanupFunctionOp{} }
func (m *CleanupFunctionOp) String() string { return proto.CompactTextString(m) }
func (*CleanupFunctionOp) ProtoMessage()    {}
func (*CleanupFunctionOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{18}
}
func (m *CleanupFunctionOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CleanupFunctionOp.Unmarshal(m, b)
}
func (m *CleanupFunctionOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CleanupFunctionOp.Marshal(b, m, deterministic)
}
func (dst *CleanupFunctionOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CleanupFunctionOp.Merge(dst, src)
}
func (m *CleanupFunctionOp) XXX_Size() int {
	return xxx_messageInfo_CleanupFunctionOp.Size(m)
}
func (m *CleanupFunctionOp) XXX_DiscardUnknown() {
	xxx_messageInfo_CleanupFunctionOp.DiscardUnknown(m)
}

var xxx_messageInfo_CleanupFunctionOp proto.InternalMessageInfo

func (m *CleanupFunctionOp) GetStepId() int64 {
	if m != nil {
		return m.StepId
	}
	return 0
}

type SyncRemoteExecutorForStream struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncRemoteExecutorForStream) Reset()         { *m = SyncRemoteExecutorForStream{} }
func (m *SyncRemoteExecutorForStream) String() string { return proto.CompactTextString(m) }
func (*SyncRemoteExecutorForStream) ProtoMessage()    {}
func (*SyncRemoteExecutorForStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{19}
}
func (m *SyncRemoteExecutorForStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncRemoteExecutorForStream.Unmarshal(m, b)
}
func (m *SyncRemoteExecutorForStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncRemoteExecutorForStream.Marshal(b, m, deterministic)
}
func (dst *SyncRemoteExecutorForStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncRemoteExecutorForStream.Merge(dst, src)
}
func (m *SyncRemoteExecutorForStream) XXX_Size() int {
	return xxx_messageInfo_SyncRemoteExecutorForStream.Size(m)
}
func (m *SyncRemoteExecutorForStream) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncRemoteExecutorForStream.DiscardUnknown(m)
}

var xxx_messageInfo_SyncRemoteExecutorForStream proto.InternalMessageInfo

type SendTensorOp struct {
	// All remote tensors are identified by <Op ID, Output num>. To mimic this
	// situation when directly sending tensors, we include an "artificial" op ID
	// (which would have corresponded to the _Recv op when not using SendTensor).
	OpId int64 `protobuf:"varint,1,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	// The index within the repeated field is the output number that will help
	// uniquely identify (along with the above op_id) the particular tensor.
	Tensors []*tensor_go_proto.TensorProto `protobuf:"bytes,2,rep,name=tensors,proto3" json:"tensors,omitempty"`
	// The device on which the tensors should be resident.
	DeviceName           string   `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTensorOp) Reset()         { *m = SendTensorOp{} }
func (m *SendTensorOp) String() string { return proto.CompactTextString(m) }
func (*SendTensorOp) ProtoMessage()    {}
func (*SendTensorOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{20}
}
func (m *SendTensorOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTensorOp.Unmarshal(m, b)
}
func (m *SendTensorOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTensorOp.Marshal(b, m, deterministic)
}
func (dst *SendTensorOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTensorOp.Merge(dst, src)
}
func (m *SendTensorOp) XXX_Size() int {
	return xxx_messageInfo_SendTensorOp.Size(m)
}
func (m *SendTensorOp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTensorOp.DiscardUnknown(m)
}

var xxx_messageInfo_SendTensorOp proto.InternalMessageInfo

func (m *SendTensorOp) GetOpId() int64 {
	if m != nil {
		return m.OpId
	}
	return 0
}

func (m *SendTensorOp) GetTensors() []*tensor_go_proto.TensorProto {
	if m != nil {
		return m.Tensors
	}
	return nil
}

func (m *SendTensorOp) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

// Send a packed TensorHandle to a remote worker.
type SendPackedHandleOp struct {
	// Op id of the remote packed TensorHandle.
	OpId                 int64                        `protobuf:"varint,1,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	Handles              []*SendPackedHandleOp_Handle `protobuf:"bytes,2,rep,name=handles,proto3" json:"handles,omitempty"`
	DeviceName           string                       `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SendPackedHandleOp) Reset()         { *m = SendPackedHandleOp{} }
func (m *SendPackedHandleOp) String() string { return proto.CompactTextString(m) }
func (*SendPackedHandleOp) ProtoMessage()    {}
func (*SendPackedHandleOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{21}
}
func (m *SendPackedHandleOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPackedHandleOp.Unmarshal(m, b)
}
func (m *SendPackedHandleOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPackedHandleOp.Marshal(b, m, deterministic)
}
func (dst *SendPackedHandleOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPackedHandleOp.Merge(dst, src)
}
func (m *SendPackedHandleOp) XXX_Size() int {
	return xxx_messageInfo_SendPackedHandleOp.Size(m)
}
func (m *SendPackedHandleOp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPackedHandleOp.DiscardUnknown(m)
}

var xxx_messageInfo_SendPackedHandleOp proto.InternalMessageInfo

func (m *SendPackedHandleOp) GetOpId() int64 {
	if m != nil {
		return m.OpId
	}
	return 0
}

func (m *SendPackedHandleOp) GetHandles() []*SendPackedHandleOp_Handle {
	if m != nil {
		return m.Handles
	}
	return nil
}

func (m *SendPackedHandleOp) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

type SendPackedHandleOp_LocalTensorHandle struct {
	Tensor *tensor_go_proto.TensorProto `protobuf:"bytes,1,opt,name=tensor,proto3" json:"tensor,omitempty"`
	// Device where the tensor is produced.
	Device               string   `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPackedHandleOp_LocalTensorHandle) Reset()         { *m = SendPackedHandleOp_LocalTensorHandle{} }
func (m *SendPackedHandleOp_LocalTensorHandle) String() string { return proto.CompactTextString(m) }
func (*SendPackedHandleOp_LocalTensorHandle) ProtoMessage()    {}
func (*SendPackedHandleOp_LocalTensorHandle) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{21, 0}
}
func (m *SendPackedHandleOp_LocalTensorHandle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPackedHandleOp_LocalTensorHandle.Unmarshal(m, b)
}
func (m *SendPackedHandleOp_LocalTensorHandle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPackedHandleOp_LocalTensorHandle.Marshal(b, m, deterministic)
}
func (dst *SendPackedHandleOp_LocalTensorHandle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPackedHandleOp_LocalTensorHandle.Merge(dst, src)
}
func (m *SendPackedHandleOp_LocalTensorHandle) XXX_Size() int {
	return xxx_messageInfo_SendPackedHandleOp_LocalTensorHandle.Size(m)
}
func (m *SendPackedHandleOp_LocalTensorHandle) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPackedHandleOp_LocalTensorHandle.DiscardUnknown(m)
}

var xxx_messageInfo_SendPackedHandleOp_LocalTensorHandle proto.InternalMessageInfo

func (m *SendPackedHandleOp_LocalTensorHandle) GetTensor() *tensor_go_proto.TensorProto {
	if m != nil {
		return m.Tensor
	}
	return nil
}

func (m *SendPackedHandleOp_LocalTensorHandle) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

type SendPackedHandleOp_Handle struct {
	// Types that are valid to be assigned to Item:
	//	*SendPackedHandleOp_Handle_LocalHandle
	//	*SendPackedHandleOp_Handle_RemoteHandle
	Item                 isSendPackedHandleOp_Handle_Item `protobuf_oneof:"item"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *SendPackedHandleOp_Handle) Reset()         { *m = SendPackedHandleOp_Handle{} }
func (m *SendPackedHandleOp_Handle) String() string { return proto.CompactTextString(m) }
func (*SendPackedHandleOp_Handle) ProtoMessage()    {}
func (*SendPackedHandleOp_Handle) Descriptor() ([]byte, []int) {
	return fileDescriptor_eager_service_3604048bc6361d18, []int{21, 1}
}
func (m *SendPackedHandleOp_Handle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPackedHandleOp_Handle.Unmarshal(m, b)
}
func (m *SendPackedHandleOp_Handle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPackedHandleOp_Handle.Marshal(b, m, deterministic)
}
func (dst *SendPackedHandleOp_Handle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPackedHandleOp_Handle.Merge(dst, src)
}
func (m *SendPackedHandleOp_Handle) XXX_Size() int {
	return xxx_messageInfo_SendPackedHandleOp_Handle.Size(m)
}
func (m *SendPackedHandleOp_Handle) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPackedHandleOp_Handle.DiscardUnknown(m)
}

var xxx_messageInfo_SendPackedHandleOp_Handle proto.InternalMessageInfo

type isSendPackedHandleOp_Handle_Item interface {
	isSendPackedHandleOp_Handle_Item()
}

type SendPackedHandleOp_Handle_LocalHandle struct {
	LocalHandle *SendPackedHandleOp_LocalTensorHandle `protobuf:"bytes,1,opt,name=local_handle,json=localHandle,proto3,oneof"`
}

type SendPackedHandleOp_Handle_RemoteHandle struct {
	RemoteHandle *RemoteTensorHandle `protobuf:"bytes,2,opt,name=remote_handle,json=remoteHandle,proto3,oneof"`
}

func (*SendPackedHandleOp_Handle_LocalHandle) isSendPackedHandleOp_Handle_Item() {}

func (*SendPackedHandleOp_Handle_RemoteHandle) isSendPackedHandleOp_Handle_Item() {}

func (m *SendPackedHandleOp_Handle) GetItem() isSendPackedHandleOp_Handle_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *SendPackedHandleOp_Handle) GetLocalHandle() *SendPackedHandleOp_LocalTensorHandle {
	if x, ok := m.GetItem().(*SendPackedHandleOp_Handle_LocalHandle); ok {
		return x.LocalHandle
	}
	return nil
}

func (m *SendPackedHandleOp_Handle) GetRemoteHandle() *RemoteTensorHandle {
	if x, ok := m.GetItem().(*SendPackedHandleOp_Handle_RemoteHandle); ok {
		return x.RemoteHandle
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SendPackedHandleOp_Handle) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SendPackedHandleOp_Handle_OneofMarshaler, _SendPackedHandleOp_Handle_OneofUnmarshaler, _SendPackedHandleOp_Handle_OneofSizer, []interface{}{
		(*SendPackedHandleOp_Handle_LocalHandle)(nil),
		(*SendPackedHandleOp_Handle_RemoteHandle)(nil),
	}
}

func _SendPackedHandleOp_Handle_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SendPackedHandleOp_Handle)
	// item
	switch x := m.Item.(type) {
	case *SendPackedHandleOp_Handle_LocalHandle:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LocalHandle); err != nil {
			return err
		}
	case *SendPackedHandleOp_Handle_RemoteHandle:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RemoteHandle); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SendPackedHandleOp_Handle.Item has unexpected type %T", x)
	}
	return nil
}

func _SendPackedHandleOp_Handle_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SendPackedHandleOp_Handle)
	switch tag {
	case 1: // item.local_handle
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SendPackedHandleOp_LocalTensorHandle)
		err := b.DecodeMessage(msg)
		m.Item = &SendPackedHandleOp_Handle_LocalHandle{msg}
		return true, err
	case 2: // item.remote_handle
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RemoteTensorHandle)
		err := b.DecodeMessage(msg)
		m.Item = &SendPackedHandleOp_Handle_RemoteHandle{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SendPackedHandleOp_Handle_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SendPackedHandleOp_Handle)
	// item
	switch x := m.Item.(type) {
	case *SendPackedHandleOp_Handle_LocalHandle:
		s := proto.Size(x.LocalHandle)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SendPackedHandleOp_Handle_RemoteHandle:
		s := proto.Size(x.RemoteHandle)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Operation)(nil), "tensorflow.eager.Operation")
	proto.RegisterMapType((map[string]*attr_value_go_proto.AttrValue)(nil), "tensorflow.eager.Operation.AttrsEntry")
	proto.RegisterType((*Operation_Input)(nil), "tensorflow.eager.Operation.Input")
	proto.RegisterType((*QueueItem)(nil), "tensorflow.eager.QueueItem")
	proto.RegisterType((*QueueResponse)(nil), "tensorflow.eager.QueueResponse")
	proto.RegisterType((*CreateContextRequest)(nil), "tensorflow.eager.CreateContextRequest")
	proto.RegisterType((*CreateContextResponse)(nil), "tensorflow.eager.CreateContextResponse")
	proto.RegisterType((*UpdateContextRequest)(nil), "tensorflow.eager.UpdateContextRequest")
	proto.RegisterType((*UpdateContextResponse)(nil), "tensorflow.eager.UpdateContextResponse")
	proto.RegisterType((*EnqueueRequest)(nil), "tensorflow.eager.EnqueueRequest")
	proto.RegisterType((*EnqueueResponse)(nil), "tensorflow.eager.EnqueueResponse")
	proto.RegisterType((*WaitQueueDoneRequest)(nil), "tensorflow.eager.WaitQueueDoneRequest")
	proto.RegisterType((*WaitQueueDoneResponse)(nil), "tensorflow.eager.WaitQueueDoneResponse")
	proto.RegisterType((*RunComponentFunctionRequest)(nil), "tensorflow.eager.RunComponentFunctionRequest")
	proto.RegisterType((*RunComponentFunctionResponse)(nil), "tensorflow.eager.RunComponentFunctionResponse")
	proto.RegisterType((*KeepAliveRequest)(nil), "tensorflow.eager.KeepAliveRequest")
	proto.RegisterType((*KeepAliveResponse)(nil), "tensorflow.eager.KeepAliveResponse")
	proto.RegisterType((*CloseContextRequest)(nil), "tensorflow.eager.CloseContextRequest")
	proto.RegisterType((*CloseContextResponse)(nil), "tensorflow.eager.CloseContextResponse")
	proto.RegisterType((*RegisterFunctionOp)(nil), "tensorflow.eager.RegisterFunctionOp")
	proto.RegisterType((*CleanupFunctionOp)(nil), "tensorflow.eager.CleanupFunctionOp")
	proto.RegisterType((*SyncRemoteExecutorForStream)(nil), "tensorflow.eager.SyncRemoteExecutorForStream")
	proto.RegisterType((*SendTensorOp)(nil), "tensorflow.eager.SendTensorOp")
	proto.RegisterType((*SendPackedHandleOp)(nil), "tensorflow.eager.SendPackedHandleOp")
	proto.RegisterType((*SendPackedHandleOp_LocalTensorHandle)(nil), "tensorflow.eager.SendPackedHandleOp.LocalTensorHandle")
	proto.RegisterType((*SendPackedHandleOp_Handle)(nil), "tensorflow.eager.SendPackedHandleOp.Handle")
}

func init() {
	proto.RegisterFile("tensorflow/core/protobuf/eager_service.proto", fileDescriptor_eager_service_3604048bc6361d18)
}

var fileDescriptor_eager_service_3604048bc6361d18 = []byte{
	// 1565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x5b, 0x73, 0xd3, 0x46,
	0x14, 0x8e, 0x7c, 0x4b, 0x7c, 0x9c, 0x04, 0x67, 0x49, 0x88, 0xeb, 0x40, 0x31, 0x82, 0xa6, 0x99,
	0x42, 0x1d, 0x12, 0x3a, 0x2d, 0x85, 0x4e, 0x67, 0x42, 0x2e, 0x63, 0x07, 0x86, 0xd0, 0x75, 0x4a,
	0x2f, 0xd0, 0x11, 0x8a, 0xb4, 0x4e, 0x34, 0xb1, 0xb5, 0x42, 0x2b, 0x25, 0xb8, 0xaf, 0x7d, 0xee,
	0xf4, 0x8f, 0xf4, 0xa9, 0x8f, 0x7d, 0xe8, 0x1f, 0xe8, 0x2f, 0xe8, 0x8f, 0xe8, 0x7f, 0xe8, 0xec,
	0x45, 0xbe, 0x49, 0x76, 0x0c, 0xc3, 0xf4, 0x25, 0x59, 0x9d, 0xfd, 0xce, 0x39, 0x7b, 0x6e, 0x7b,
	0xce, 0x1a, 0xee, 0x04, 0xc4, 0x65, 0xd4, 0x6f, 0xb6, 0xe8, 0xf9, 0xba, 0x45, 0x7d, 0xb2, 0xee,
	0xf9, 0x34, 0xa0, 0x47, 0x61, 0x73, 0x9d, 0x98, 0xc7, 0xc4, 0x37, 0x18, 0xf1, 0xcf, 0x1c, 0x8b,
	0x54, 0x05, 0x19, 0x15, 0x7b, 0xe8, 0xaa, 0xd8, 0x2f, 0x7f, 0x32, 0xcc, 0xdf, 0xf4, 0xcd, 0x36,
	0x39, 0xa7, 0xfe, 0xe9, 0xba, 0x19, 0x04, 0xbe, 0x71, 0x66, 0xb6, 0x42, 0xc5, 0x5d, 0xde, 0x18,
	0x8d, 0xb5, 0x09, 0xd7, 0x62, 0x70, 0x16, 0xe7, 0x28, 0x0c, 0x08, 0x53, 0x2c, 0x6b, 0xa3, 0x59,
	0x9a, 0xa1, 0x6b, 0x05, 0x0e, 0x75, 0x15, 0x72, 0x75, 0x34, 0x52, 0xee, 0x28, 0xdc, 0x9d, 0x8b,
	0x70, 0x06, 0x3b, 0x31, 0x3d, 0x72, 0xb1, 0xfe, 0x33, 0xe2, 0x33, 0x87, 0xba, 0xd1, 0x49, 0xef,
	0x8d, 0x74, 0xa4, 0x4f, 0xda, 0x34, 0x20, 0x86, 0x92, 0x7e, 0x62, 0xba, 0x76, 0x2b, 0x12, 0x7f,
	0x77, 0x24, 0x53, 0x6f, 0x43, 0x84, 0x80, 0xa8, 0xe3, 0xeb, 0x7f, 0x67, 0x20, 0x7f, 0xe0, 0x11,
	0xdf, 0xe4, 0xa6, 0xa3, 0x79, 0x48, 0x39, 0x76, 0x49, 0xab, 0x68, 0x6b, 0x69, 0x9c, 0x72, 0x6c,
	0x84, 0x20, 0xe3, 0x9a, 0x6d, 0x52, 0x4a, 0x55, 0xb4, 0xb5, 0x3c, 0x16, 0x6b, 0xf4, 0x35, 0xe4,
	0xa9, 0x67, 0x38, 0xae, 0x17, 0x06, 0xac, 0x04, 0x95, 0xf4, 0x5a, 0x61, 0xf3, 0x46, 0x75, 0x38,
	0x8e, 0xd5, 0xae, 0xcc, 0x6a, 0x9d, 0x23, 0xf1, 0x0c, 0xf5, 0xc4, 0x82, 0xa1, 0x5b, 0x30, 0x6f,
	0x51, 0x37, 0xf0, 0x69, 0xcb, 0xe0, 0x72, 0x6c, 0x56, 0xca, 0x54, 0xd2, 0x6b, 0x69, 0x3c, 0xab,
	0xa8, 0x07, 0x5e, 0xdd, 0x66, 0xe8, 0x2b, 0xc8, 0xf2, 0xe0, 0xb1, 0x52, 0x56, 0x68, 0x58, 0x1d,
	0xa7, 0x61, 0x8b, 0x03, 0x77, 0xdd, 0xc0, 0xef, 0x60, 0xc9, 0x84, 0xae, 0x40, 0x4e, 0x66, 0x40,
	0x29, 0x27, 0x4e, 0xae, 0xbe, 0xd0, 0x26, 0x2c, 0x39, 0xcc, 0xb0, 0x68, 0xdb, 0xa3, 0x2e, 0x71,
	0x03, 0x23, 0x8a, 0x79, 0x69, 0xba, 0xa2, 0xad, 0xcd, 0xe0, 0xcb, 0x0e, 0xdb, 0x8e, 0xf6, 0xf6,
	0xd4, 0x16, 0xaa, 0xc0, 0x2c, 0x87, 0x19, 0x2c, 0x20, 0xfc, 0xb8, 0xa5, 0x19, 0xe1, 0x1d, 0xe0,
	0xb4, 0x46, 0x40, 0xbc, 0xba, 0x8d, 0xae, 0x43, 0xc1, 0x61, 0x3d, 0x59, 0x79, 0x21, 0x0b, 0x1c,
	0x16, 0x89, 0x28, 0xff, 0xa6, 0x41, 0x56, 0x58, 0x8f, 0x1e, 0xc3, 0x9c, 0x0a, 0x9f, 0x8c, 0x9b,
	0xf0, 0x75, 0x61, 0xf3, 0x56, 0xdc, 0x3c, 0x2c, 0x60, 0x87, 0x82, 0x5c, 0x13, 0xd8, 0xda, 0x14,
	0x9e, 0x95, 0xcc, 0xf2, 0x1b, 0x6d, 0x40, 0x4e, 0xb2, 0x89, 0xf8, 0x14, 0x36, 0x97, 0xfb, 0xa5,
	0x48, 0xce, 0x67, 0x3c, 0xc8, 0xb5, 0x29, 0xac, 0x80, 0x8f, 0x72, 0x90, 0x71, 0x02, 0xd2, 0x2e,
	0x1f, 0x00, 0xf4, 0xbc, 0x86, 0x8a, 0x90, 0x3e, 0x25, 0x1d, 0x71, 0x96, 0x3c, 0xe6, 0x4b, 0x74,
	0x1b, 0xb2, 0xa2, 0xd2, 0x94, 0xe4, 0xa5, 0x7e, 0xc9, 0x9c, 0xf1, 0x39, 0xdf, 0xc4, 0x12, 0xf3,
	0x20, 0x75, 0x5f, 0xdb, 0xcf, 0xcc, 0xa4, 0x8b, 0x19, 0xfd, 0x9f, 0x0c, 0xe4, 0xbf, 0x09, 0x49,
	0x48, 0xea, 0x01, 0x69, 0xa3, 0x67, 0x50, 0x94, 0x56, 0x1a, 0x01, 0x35, 0x6c, 0x62, 0xf9, 0xa4,
	0xf9, 0x96, 0xf6, 0xce, 0x4b, 0xfe, 0x43, 0xba, 0x23, 0xb8, 0xd1, 0x43, 0x9e, 0x7b, 0x2a, 0xec,
	0xea, 0x68, 0x2b, 0x63, 0x32, 0xa3, 0x36, 0x85, 0x7b, 0x78, 0xb4, 0x05, 0x05, 0x46, 0x5c, 0x5b,
	0x15, 0x4e, 0x29, 0x2d, 0xd8, 0x3f, 0x8c, 0xb3, 0x37, 0x88, 0x6b, 0xcb, 0x73, 0x1c, 0x78, 0xb5,
	0x29, 0x0c, 0xac, 0xfb, 0x8d, 0x1a, 0xb0, 0xe0, 0x93, 0x63, 0x87, 0x05, 0xc4, 0xef, 0xc5, 0x3b,
	0x33, 0xda, 0x24, 0x09, 0x8d, 0xf2, 0x40, 0x88, 0x2b, 0xfa, 0x43, 0x54, 0xee, 0x26, 0xab, 0x45,
	0x4c, 0x37, 0xf4, 0x7a, 0x32, 0xb3, 0x42, 0xe6, 0xcd, 0xb8, 0xcc, 0x6d, 0x89, 0x1c, 0x10, 0x79,
	0xc9, 0x1a, 0x24, 0xa2, 0x10, 0xae, 0xb3, 0x8e, 0x6b, 0x19, 0x2a, 0xd5, 0xc8, 0x1b, 0x62, 0x85,
	0x01, 0xf5, 0x8d, 0x26, 0xbf, 0x8d, 0x02, 0x9f, 0x98, 0x6d, 0x51, 0x17, 0x85, 0xcd, 0x4f, 0x13,
	0xac, 0xef, 0xb8, 0x96, 0x8c, 0xc5, 0xae, 0x62, 0xdb, 0xa3, 0x7e, 0x43, 0x30, 0xd5, 0xa6, 0xf0,
	0x0a, 0x1b, 0xbd, 0x8d, 0x0e, 0x01, 0x09, 0x07, 0x7b, 0xa6, 0x75, 0x4a, 0xec, 0x28, 0xc3, 0xa7,
	0x47, 0xb9, 0x87, 0xfb, 0xf9, 0x99, 0x80, 0xca, 0x78, 0x4b, 0xf7, 0xb0, 0x21, 0x6a, 0x94, 0xb2,
	0x7a, 0x00, 0x73, 0x22, 0xb5, 0x30, 0x61, 0x1e, 0x75, 0x19, 0x2f, 0xe6, 0xac, 0xb8, 0x5a, 0x4b,
	0x9a, 0xb8, 0x22, 0xae, 0xc6, 0xb3, 0xbf, 0xc1, 0xb7, 0x45, 0x09, 0x60, 0x09, 0x45, 0xeb, 0x7d,
	0x25, 0x93, 0x1e, 0x53, 0x32, 0x51, 0xc1, 0xe8, 0x7f, 0xa4, 0x61, 0x71, 0xdb, 0x27, 0x66, 0x40,
	0xb6, 0xa9, 0x1b, 0x90, 0x37, 0x01, 0x26, 0xaf, 0x43, 0xc2, 0x02, 0xf4, 0x19, 0x80, 0xbc, 0x48,
	0x0d, 0xbb, 0x9b, 0xd6, 0x03, 0x65, 0xd2, 0x10, 0xbb, 0x3b, 0xa4, 0x89, 0xf3, 0x2c, 0x5a, 0xa2,
	0x45, 0xc8, 0x9a, 0xdc, 0x85, 0x22, 0x79, 0x67, 0xb0, 0xfc, 0x40, 0xab, 0x70, 0xe9, 0x94, 0x10,
	0xcf, 0x30, 0x5b, 0xce, 0x19, 0x31, 0x18, 0xb1, 0x98, 0xc8, 0xce, 0x34, 0x9e, 0xe3, 0xe4, 0x2d,
	0x4e, 0x6d, 0x10, 0x8b, 0xa1, 0x2f, 0xa0, 0xa0, 0xba, 0x84, 0x50, 0x2a, 0x13, 0xef, 0x4a, 0xbf,
	0xd2, 0xe7, 0x72, 0x9b, 0x6b, 0x85, 0xb3, 0xee, 0x1a, 0x7d, 0x0f, 0x1f, 0x58, 0xad, 0x50, 0xa4,
	0x6d, 0xac, 0x33, 0x96, 0x72, 0x71, 0xf7, 0xed, 0x08, 0xd0, 0x56, 0x17, 0x83, 0x97, 0x15, 0xfb,
	0xf0, 0x06, 0xba, 0x06, 0x60, 0x49, 0xc7, 0xf0, 0xbb, 0x91, 0xc7, 0x3a, 0x87, 0xf3, 0x8a, 0x52,
	0xb7, 0xb9, 0x65, 0xd1, 0xf6, 0x99, 0x43, 0xce, 0xa3, 0xfb, 0x33, 0x87, 0xe7, 0x14, 0xf9, 0xb9,
	0x43, 0xce, 0xeb, 0x36, 0xda, 0x83, 0x4a, 0xcb, 0xfc, 0xb9, 0x63, 0x58, 0xd4, 0xeb, 0x44, 0x69,
	0x1b, 0x15, 0x43, 0xd4, 0x6b, 0xe4, 0xbd, 0x7a, 0x95, 0xe3, 0xb6, 0xa9, 0xd7, 0x91, 0x59, 0x18,
	0xe5, 0xbc, 0x6c, 0x2e, 0xfb, 0x99, 0x99, 0x6c, 0x31, 0xa7, 0x9f, 0xc0, 0xd2, 0x50, 0xcc, 0x54,
	0xca, 0xd4, 0x61, 0x21, 0x6e, 0x7f, 0x6a, 0x02, 0xfb, 0x8b, 0xf6, 0x10, 0x65, 0x3f, 0x33, 0xa3,
	0x15, 0x53, 0xfa, 0xbf, 0x1a, 0x2c, 0x7e, 0xeb, 0xd9, 0xef, 0x2b, 0x3d, 0xc6, 0xc6, 0x29, 0xf5,
	0xfe, 0xe2, 0x94, 0x9e, 0x20, 0x4e, 0x99, 0x84, 0x38, 0xe9, 0x47, 0xb0, 0x34, 0x64, 0xee, 0x38,
	0xcf, 0x6a, 0xef, 0xe2, 0x59, 0xfd, 0x08, 0xe6, 0x77, 0xdd, 0xd7, 0xb2, 0xd4, 0xa5, 0x33, 0x07,
	0x0f, 0xaf, 0x0d, 0x1f, 0x7e, 0x03, 0xb2, 0x02, 0x5e, 0x4a, 0x0b, 0x7d, 0x09, 0x1d, 0xa1, 0xdb,
	0x93, 0xb0, 0x44, 0xea, 0x3f, 0xc0, 0xa5, 0xae, 0x0e, 0x65, 0xc1, 0x1e, 0xcc, 0x0b, 0x82, 0xe1,
	0x2b, 0x8a, 0x3a, 0xfe, 0xf5, 0x11, 0xe2, 0x22, 0x46, 0x3c, 0x37, 0x20, 0x47, 0xdf, 0x87, 0xc5,
	0xef, 0x4c, 0x27, 0x10, 0x98, 0x1d, 0xea, 0x4e, 0x6a, 0xc4, 0x65, 0xc8, 0x8a, 0x71, 0x48, 0x84,
	0x39, 0x8d, 0x33, 0xd4, 0xab, 0xdb, 0xfa, 0x32, 0x2c, 0x0d, 0xc9, 0x52, 0x4a, 0xce, 0x61, 0x05,
	0x87, 0x6e, 0x6c, 0x58, 0x99, 0x50, 0xd7, 0x97, 0x6f, 0xd7, 0x46, 0xfb, 0x9a, 0xa8, 0xfe, 0x8b,
	0x06, 0x57, 0x93, 0x35, 0xff, 0x9f, 0xb7, 0xf2, 0x06, 0x14, 0x1f, 0x47, 0x37, 0xe3, 0x64, 0x36,
	0xeb, 0x0f, 0x61, 0xa1, 0x8f, 0x45, 0x1d, 0x36, 0x21, 0xed, 0xb5, 0xa4, 0xb4, 0x7f, 0x09, 0x97,
	0xb7, 0x5b, 0x94, 0x0d, 0x17, 0xf9, 0x05, 0x6e, 0x4e, 0x90, 0x9e, 0x4a, 0x92, 0x7e, 0x05, 0x16,
	0x07, 0xa5, 0xab, 0x20, 0xff, 0xa5, 0x01, 0x8a, 0xcf, 0x10, 0xe8, 0x81, 0x1c, 0x48, 0x83, 0xa8,
	0x0d, 0x68, 0xf1, 0xe1, 0x2f, 0x42, 0xf3, 0xeb, 0xa5, 0xd0, 0xec, 0x7d, 0x8c, 0x1e, 0x80, 0x53,
	0xa3, 0x07, 0xe0, 0xfb, 0x30, 0xdd, 0x72, 0x8e, 0x7c, 0xd3, 0xef, 0x24, 0xcd, 0x4c, 0x7d, 0xaa,
	0x9e, 0x48, 0x14, 0x8e, 0xe0, 0xfa, 0x1d, 0x58, 0x88, 0xcd, 0x2b, 0x68, 0x19, 0xa6, 0xa3, 0x51,
	0x5a, 0x3e, 0x34, 0x72, 0x4c, 0x8c, 0xd1, 0xfa, 0x35, 0x58, 0x19, 0x33, 0x7c, 0xe8, 0xe7, 0x30,
	0xdb, 0x3f, 0x99, 0xf5, 0x0a, 0x46, 0x4a, 0x11, 0x05, 0x83, 0x36, 0x60, 0x5a, 0x9e, 0x8d, 0x5d,
	0x94, 0x4a, 0x11, 0x8e, 0x4f, 0xef, 0xea, 0xe6, 0x12, 0x4f, 0x9d, 0xb4, 0x18, 0x82, 0x41, 0x92,
	0x9e, 0x9a, 0x6d, 0xa2, 0xff, 0x9e, 0x06, 0x14, 0x9f, 0x55, 0x92, 0xf5, 0xef, 0xc2, 0xb4, 0x1c,
	0x7b, 0x22, 0xfd, 0xb7, 0x27, 0x99, 0x7b, 0xaa, 0x72, 0x81, 0x23, 0xde, 0x0b, 0xcf, 0x54, 0x7e,
	0x09, 0x0b, 0x4f, 0xa8, 0x65, 0xb6, 0xfa, 0xe7, 0xe5, 0xbe, 0x32, 0xd2, 0xc6, 0xbe, 0x07, 0xa2,
	0x32, 0xea, 0x7b, 0x26, 0xa5, 0xfa, 0x9f, 0x49, 0xe5, 0x3f, 0x35, 0xc8, 0x29, 0x99, 0x2f, 0x60,
	0xb6, 0xc5, 0x15, 0x0d, 0xbe, 0x57, 0x3e, 0x9f, 0xc8, 0xaa, 0xd8, 0x09, 0x6b, 0x53, 0xb8, 0x20,
	0xa4, 0x29, 0xe1, 0xb1, 0xd7, 0x50, 0xea, 0xdd, 0x5f, 0x43, 0xd1, 0x9c, 0xb8, 0xf9, 0x6b, 0x0e,
	0x66, 0x77, 0x39, 0x53, 0x43, 0xfe, 0xd4, 0x80, 0x5e, 0xc1, 0xdc, 0xc0, 0x34, 0x80, 0x12, 0x1e,
	0x93, 0x49, 0x23, 0x5e, 0xf9, 0xe3, 0x0b, 0x71, 0xea, 0x1a, 0x79, 0x05, 0x73, 0x03, 0x5d, 0x31,
	0x49, 0x43, 0xd2, 0x94, 0x90, 0xa4, 0x21, 0xb9, 0xbd, 0x3e, 0x85, 0x69, 0xd5, 0xaf, 0x50, 0x25,
	0xce, 0x33, 0xd8, 0x2e, 0xcb, 0x37, 0xc6, 0x20, 0x94, 0xbc, 0x17, 0x50, 0x94, 0x65, 0xe5, 0xb8,
	0xc7, 0xef, 0x53, 0xf0, 0x9a, 0x76, 0x57, 0xe3, 0xee, 0x18, 0xe8, 0x5a, 0x49, 0xee, 0x48, 0x6a,
	0x91, 0x49, 0xee, 0x48, 0x6c, 0x7f, 0x28, 0x84, 0xc5, 0xa4, 0x26, 0x84, 0x12, 0xde, 0x33, 0x63,
	0xda, 0x64, 0xb9, 0x3a, 0x29, 0x5c, 0xa9, 0x3d, 0x84, 0x7c, 0xb7, 0x87, 0x20, 0x3d, 0xce, 0x3c,
	0xdc, 0x93, 0xca, 0x37, 0xc7, 0x62, 0x94, 0xd4, 0x9f, 0x60, 0xb6, 0xff, 0xfa, 0x47, 0x1f, 0x25,
	0xbd, 0xfa, 0x62, 0xcd, 0xa7, 0xbc, 0x7a, 0x11, 0x4c, 0x8a, 0x7f, 0xb4, 0xff, 0x63, 0xed, 0xd8,
	0x09, 0x4e, 0xc2, 0xa3, 0xaa, 0x45, 0xdb, 0x7d, 0xbf, 0x03, 0x8d, 0x58, 0x1e, 0x53, 0xf9, 0xcb,
	0x11, 0xff, 0x63, 0x88, 0xdf, 0x88, 0x98, 0x71, 0x4c, 0xe5, 0xea, 0x28, 0x27, 0xfe, 0xdd, 0xfb,
	0x2f, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x79, 0x1a, 0x5a, 0xe6, 0x13, 0x00, 0x00,
}
