// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/protobuf/struct.proto

package core_protos_go_proto // import "github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import tensor_go_proto "github.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor_go_proto"
import tensor_shape_go_proto "github.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor_shape_go_proto"
import types_go_proto "github.com/tensorflow/tensorflow/tensorflow/go/core/framework/types_go_proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TypeSpecProto_TypeSpecClass int32

const (
	TypeSpecProto_UNKNOWN             TypeSpecProto_TypeSpecClass = 0
	TypeSpecProto_SPARSE_TENSOR_SPEC  TypeSpecProto_TypeSpecClass = 1
	TypeSpecProto_INDEXED_SLICES_SPEC TypeSpecProto_TypeSpecClass = 2
	TypeSpecProto_RAGGED_TENSOR_SPEC  TypeSpecProto_TypeSpecClass = 3
	TypeSpecProto_TENSOR_ARRAY_SPEC   TypeSpecProto_TypeSpecClass = 4
	TypeSpecProto_DATA_DATASET_SPEC   TypeSpecProto_TypeSpecClass = 5
	TypeSpecProto_DATA_ITERATOR_SPEC  TypeSpecProto_TypeSpecClass = 6
	TypeSpecProto_OPTIONAL_SPEC       TypeSpecProto_TypeSpecClass = 7
	TypeSpecProto_PER_REPLICA_SPEC    TypeSpecProto_TypeSpecClass = 8
	TypeSpecProto_VARIABLE_SPEC       TypeSpecProto_TypeSpecClass = 9
	TypeSpecProto_ROW_PARTITION_SPEC  TypeSpecProto_TypeSpecClass = 10
)

var TypeSpecProto_TypeSpecClass_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "SPARSE_TENSOR_SPEC",
	2:  "INDEXED_SLICES_SPEC",
	3:  "RAGGED_TENSOR_SPEC",
	4:  "TENSOR_ARRAY_SPEC",
	5:  "DATA_DATASET_SPEC",
	6:  "DATA_ITERATOR_SPEC",
	7:  "OPTIONAL_SPEC",
	8:  "PER_REPLICA_SPEC",
	9:  "VARIABLE_SPEC",
	10: "ROW_PARTITION_SPEC",
}
var TypeSpecProto_TypeSpecClass_value = map[string]int32{
	"UNKNOWN":             0,
	"SPARSE_TENSOR_SPEC":  1,
	"INDEXED_SLICES_SPEC": 2,
	"RAGGED_TENSOR_SPEC":  3,
	"TENSOR_ARRAY_SPEC":   4,
	"DATA_DATASET_SPEC":   5,
	"DATA_ITERATOR_SPEC":  6,
	"OPTIONAL_SPEC":       7,
	"PER_REPLICA_SPEC":    8,
	"VARIABLE_SPEC":       9,
	"ROW_PARTITION_SPEC":  10,
}

func (x TypeSpecProto_TypeSpecClass) String() string {
	return proto.EnumName(TypeSpecProto_TypeSpecClass_name, int32(x))
}
func (TypeSpecProto_TypeSpecClass) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_struct_b79935a3b64f0a23, []int{9, 0}
}

// `StructuredValue` represents a dynamically typed value representing various
// data structures that are inspired by Python data structures typically used in
// TensorFlow functions as inputs and outputs.
//
// For example when saving a Layer there may be a `training` argument. If the
// user passes a boolean True/False, that switches between two concrete
// TensorFlow functions. In order to switch between them in the same way after
// loading the SavedModel, we need to represent "True" and "False".
//
// A more advanced example might be a function which takes a list of
// dictionaries mapping from strings to Tensors. In order to map from
// user-specified arguments `[{"a": tf.constant(1.)}, {"q": tf.constant(3.)}]`
// after load to the right saved TensorFlow function, we need to represent the
// nested structure and the strings, recording that we have a trace for anything
// matching `[{"a": tf.TensorSpec(None, tf.float32)}, {"q": tf.TensorSpec([],
// tf.float64)}]` as an example.
//
// Likewise functions may return nested structures of Tensors, for example
// returning a dictionary mapping from strings to Tensors. In order for the
// loaded function to return the same structure we need to serialize it.
//
// This is an ergonomic aid for working with loaded SavedModels, not a promise
// to serialize all possible function signatures. For example we do not expect
// to pickle generic Python objects, and ideally we'd stay language-agnostic.
type StructuredValue struct {
	// The kind of value.
	//
	// Types that are valid to be assigned to Kind:
	//	*StructuredValue_NoneValue
	//	*StructuredValue_Float64Value
	//	*StructuredValue_Int64Value
	//	*StructuredValue_StringValue
	//	*StructuredValue_BoolValue
	//	*StructuredValue_TensorShapeValue
	//	*StructuredValue_TensorDtypeValue
	//	*StructuredValue_TensorSpecValue
	//	*StructuredValue_TypeSpecValue
	//	*StructuredValue_BoundedTensorSpecValue
	//	*StructuredValue_ListValue
	//	*StructuredValue_TupleValue
	//	*StructuredValue_DictValue
	//	*StructuredValue_NamedTupleValue
	Kind                 isStructuredValue_Kind `protobuf_oneof:"kind"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StructuredValue) Reset()         { *m = StructuredValue{} }
func (m *StructuredValue) String() string { return proto.CompactTextString(m) }
func (*StructuredValue) ProtoMessage()    {}
func (*StructuredValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_struct_b79935a3b64f0a23, []int{0}
}
func (m *StructuredValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructuredValue.Unmarshal(m, b)
}
func (m *StructuredValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructuredValue.Marshal(b, m, deterministic)
}
func (dst *StructuredValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructuredValue.Merge(dst, src)
}
func (m *StructuredValue) XXX_Size() int {
	return xxx_messageInfo_StructuredValue.Size(m)
}
func (m *StructuredValue) XXX_DiscardUnknown() {
	xxx_messageInfo_StructuredValue.DiscardUnknown(m)
}

var xxx_messageInfo_StructuredValue proto.InternalMessageInfo

type isStructuredValue_Kind interface {
	isStructuredValue_Kind()
}

type StructuredValue_NoneValue struct {
	NoneValue *NoneValue `protobuf:"bytes,1,opt,name=none_value,json=noneValue,proto3,oneof"`
}

type StructuredValue_Float64Value struct {
	Float64Value float64 `protobuf:"fixed64,11,opt,name=float64_value,json=float64Value,proto3,oneof"`
}

type StructuredValue_Int64Value struct {
	Int64Value int64 `protobuf:"zigzag64,12,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type StructuredValue_StringValue struct {
	StringValue string `protobuf:"bytes,13,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type StructuredValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,14,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type StructuredValue_TensorShapeValue struct {
	TensorShapeValue *tensor_shape_go_proto.TensorShapeProto `protobuf:"bytes,31,opt,name=tensor_shape_value,json=tensorShapeValue,proto3,oneof"`
}

type StructuredValue_TensorDtypeValue struct {
	TensorDtypeValue types_go_proto.DataType `protobuf:"varint,32,opt,name=tensor_dtype_value,json=tensorDtypeValue,proto3,enum=tensorflow.DataType,oneof"`
}

type StructuredValue_TensorSpecValue struct {
	TensorSpecValue *TensorSpecProto `protobuf:"bytes,33,opt,name=tensor_spec_value,json=tensorSpecValue,proto3,oneof"`
}

type StructuredValue_TypeSpecValue struct {
	TypeSpecValue *TypeSpecProto `protobuf:"bytes,34,opt,name=type_spec_value,json=typeSpecValue,proto3,oneof"`
}

type StructuredValue_BoundedTensorSpecValue struct {
	BoundedTensorSpecValue *BoundedTensorSpecProto `protobuf:"bytes,35,opt,name=bounded_tensor_spec_value,json=boundedTensorSpecValue,proto3,oneof"`
}

type StructuredValue_ListValue struct {
	ListValue *ListValue `protobuf:"bytes,51,opt,name=list_value,json=listValue,proto3,oneof"`
}

type StructuredValue_TupleValue struct {
	TupleValue *TupleValue `protobuf:"bytes,52,opt,name=tuple_value,json=tupleValue,proto3,oneof"`
}

type StructuredValue_DictValue struct {
	DictValue *DictValue `protobuf:"bytes,53,opt,name=dict_value,json=dictValue,proto3,oneof"`
}

type StructuredValue_NamedTupleValue struct {
	NamedTupleValue *NamedTupleValue `protobuf:"bytes,54,opt,name=named_tuple_value,json=namedTupleValue,proto3,oneof"`
}

func (*StructuredValue_NoneValue) isStructuredValue_Kind() {}

func (*StructuredValue_Float64Value) isStructuredValue_Kind() {}

func (*StructuredValue_Int64Value) isStructuredValue_Kind() {}

func (*StructuredValue_StringValue) isStructuredValue_Kind() {}

func (*StructuredValue_BoolValue) isStructuredValue_Kind() {}

func (*StructuredValue_TensorShapeValue) isStructuredValue_Kind() {}

func (*StructuredValue_TensorDtypeValue) isStructuredValue_Kind() {}

func (*StructuredValue_TensorSpecValue) isStructuredValue_Kind() {}

func (*StructuredValue_TypeSpecValue) isStructuredValue_Kind() {}

func (*StructuredValue_BoundedTensorSpecValue) isStructuredValue_Kind() {}

func (*StructuredValue_ListValue) isStructuredValue_Kind() {}

func (*StructuredValue_TupleValue) isStructuredValue_Kind() {}

func (*StructuredValue_DictValue) isStructuredValue_Kind() {}

func (*StructuredValue_NamedTupleValue) isStructuredValue_Kind() {}

func (m *StructuredValue) GetKind() isStructuredValue_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *StructuredValue) GetNoneValue() *NoneValue {
	if x, ok := m.GetKind().(*StructuredValue_NoneValue); ok {
		return x.NoneValue
	}
	return nil
}

func (m *StructuredValue) GetFloat64Value() float64 {
	if x, ok := m.GetKind().(*StructuredValue_Float64Value); ok {
		return x.Float64Value
	}
	return 0
}

func (m *StructuredValue) GetInt64Value() int64 {
	if x, ok := m.GetKind().(*StructuredValue_Int64Value); ok {
		return x.Int64Value
	}
	return 0
}

func (m *StructuredValue) GetStringValue() string {
	if x, ok := m.GetKind().(*StructuredValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *StructuredValue) GetBoolValue() bool {
	if x, ok := m.GetKind().(*StructuredValue_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (m *StructuredValue) GetTensorShapeValue() *tensor_shape_go_proto.TensorShapeProto {
	if x, ok := m.GetKind().(*StructuredValue_TensorShapeValue); ok {
		return x.TensorShapeValue
	}
	return nil
}

func (m *StructuredValue) GetTensorDtypeValue() types_go_proto.DataType {
	if x, ok := m.GetKind().(*StructuredValue_TensorDtypeValue); ok {
		return x.TensorDtypeValue
	}
	return types_go_proto.DataType_DT_INVALID
}

func (m *StructuredValue) GetTensorSpecValue() *TensorSpecProto {
	if x, ok := m.GetKind().(*StructuredValue_TensorSpecValue); ok {
		return x.TensorSpecValue
	}
	return nil
}

func (m *StructuredValue) GetTypeSpecValue() *TypeSpecProto {
	if x, ok := m.GetKind().(*StructuredValue_TypeSpecValue); ok {
		return x.TypeSpecValue
	}
	return nil
}

func (m *StructuredValue) GetBoundedTensorSpecValue() *BoundedTensorSpecProto {
	if x, ok := m.GetKind().(*StructuredValue_BoundedTensorSpecValue); ok {
		return x.BoundedTensorSpecValue
	}
	return nil
}

func (m *StructuredValue) GetListValue() *ListValue {
	if x, ok := m.GetKind().(*StructuredValue_ListValue); ok {
		return x.ListValue
	}
	return nil
}

func (m *StructuredValue) GetTupleValue() *TupleValue {
	if x, ok := m.GetKind().(*StructuredValue_TupleValue); ok {
		return x.TupleValue
	}
	return nil
}

func (m *StructuredValue) GetDictValue() *DictValue {
	if x, ok := m.GetKind().(*StructuredValue_DictValue); ok {
		return x.DictValue
	}
	return nil
}

func (m *StructuredValue) GetNamedTupleValue() *NamedTupleValue {
	if x, ok := m.GetKind().(*StructuredValue_NamedTupleValue); ok {
		return x.NamedTupleValue
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*StructuredValue) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _StructuredValue_OneofMarshaler, _StructuredValue_OneofUnmarshaler, _StructuredValue_OneofSizer, []interface{}{
		(*StructuredValue_NoneValue)(nil),
		(*StructuredValue_Float64Value)(nil),
		(*StructuredValue_Int64Value)(nil),
		(*StructuredValue_StringValue)(nil),
		(*StructuredValue_BoolValue)(nil),
		(*StructuredValue_TensorShapeValue)(nil),
		(*StructuredValue_TensorDtypeValue)(nil),
		(*StructuredValue_TensorSpecValue)(nil),
		(*StructuredValue_TypeSpecValue)(nil),
		(*StructuredValue_BoundedTensorSpecValue)(nil),
		(*StructuredValue_ListValue)(nil),
		(*StructuredValue_TupleValue)(nil),
		(*StructuredValue_DictValue)(nil),
		(*StructuredValue_NamedTupleValue)(nil),
	}
}

func _StructuredValue_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*StructuredValue)
	// kind
	switch x := m.Kind.(type) {
	case *StructuredValue_NoneValue:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NoneValue); err != nil {
			return err
		}
	case *StructuredValue_Float64Value:
		b.EncodeVarint(11<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.Float64Value))
	case *StructuredValue_Int64Value:
		b.EncodeVarint(12<<3 | proto.WireVarint)
		b.EncodeZigzag64(uint64(x.Int64Value))
	case *StructuredValue_StringValue:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.StringValue)
	case *StructuredValue_BoolValue:
		t := uint64(0)
		if x.BoolValue {
			t = 1
		}
		b.EncodeVarint(14<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *StructuredValue_TensorShapeValue:
		b.EncodeVarint(31<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TensorShapeValue); err != nil {
			return err
		}
	case *StructuredValue_TensorDtypeValue:
		b.EncodeVarint(32<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.TensorDtypeValue))
	case *StructuredValue_TensorSpecValue:
		b.EncodeVarint(33<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TensorSpecValue); err != nil {
			return err
		}
	case *StructuredValue_TypeSpecValue:
		b.EncodeVarint(34<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TypeSpecValue); err != nil {
			return err
		}
	case *StructuredValue_BoundedTensorSpecValue:
		b.EncodeVarint(35<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BoundedTensorSpecValue); err != nil {
			return err
		}
	case *StructuredValue_ListValue:
		b.EncodeVarint(51<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ListValue); err != nil {
			return err
		}
	case *StructuredValue_TupleValue:
		b.EncodeVarint(52<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TupleValue); err != nil {
			return err
		}
	case *StructuredValue_DictValue:
		b.EncodeVarint(53<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DictValue); err != nil {
			return err
		}
	case *StructuredValue_NamedTupleValue:
		b.EncodeVarint(54<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NamedTupleValue); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("StructuredValue.Kind has unexpected type %T", x)
	}
	return nil
}

func _StructuredValue_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*StructuredValue)
	switch tag {
	case 1: // kind.none_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NoneValue)
		err := b.DecodeMessage(msg)
		m.Kind = &StructuredValue_NoneValue{msg}
		return true, err
	case 11: // kind.float64_value
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Kind = &StructuredValue_Float64Value{math.Float64frombits(x)}
		return true, err
	case 12: // kind.int64_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeZigzag64()
		m.Kind = &StructuredValue_Int64Value{int64(x)}
		return true, err
	case 13: // kind.string_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Kind = &StructuredValue_StringValue{x}
		return true, err
	case 14: // kind.bool_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Kind = &StructuredValue_BoolValue{x != 0}
		return true, err
	case 31: // kind.tensor_shape_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(tensor_shape_go_proto.TensorShapeProto)
		err := b.DecodeMessage(msg)
		m.Kind = &StructuredValue_TensorShapeValue{msg}
		return true, err
	case 32: // kind.tensor_dtype_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Kind = &StructuredValue_TensorDtypeValue{types_go_proto.DataType(x)}
		return true, err
	case 33: // kind.tensor_spec_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TensorSpecProto)
		err := b.DecodeMessage(msg)
		m.Kind = &StructuredValue_TensorSpecValue{msg}
		return true, err
	case 34: // kind.type_spec_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TypeSpecProto)
		err := b.DecodeMessage(msg)
		m.Kind = &StructuredValue_TypeSpecValue{msg}
		return true, err
	case 35: // kind.bounded_tensor_spec_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BoundedTensorSpecProto)
		err := b.DecodeMessage(msg)
		m.Kind = &StructuredValue_BoundedTensorSpecValue{msg}
		return true, err
	case 51: // kind.list_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ListValue)
		err := b.DecodeMessage(msg)
		m.Kind = &StructuredValue_ListValue{msg}
		return true, err
	case 52: // kind.tuple_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TupleValue)
		err := b.DecodeMessage(msg)
		m.Kind = &StructuredValue_TupleValue{msg}
		return true, err
	case 53: // kind.dict_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DictValue)
		err := b.DecodeMessage(msg)
		m.Kind = &StructuredValue_DictValue{msg}
		return true, err
	case 54: // kind.named_tuple_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NamedTupleValue)
		err := b.DecodeMessage(msg)
		m.Kind = &StructuredValue_NamedTupleValue{msg}
		return true, err
	default:
		return false, nil
	}
}

func _StructuredValue_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*StructuredValue)
	// kind
	switch x := m.Kind.(type) {
	case *StructuredValue_NoneValue:
		s := proto.Size(x.NoneValue)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StructuredValue_Float64Value:
		n += 1 // tag and wire
		n += 8
	case *StructuredValue_Int64Value:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(uint64(x.Int64Value<<1) ^ uint64((int64(x.Int64Value) >> 63))))
	case *StructuredValue_StringValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.StringValue)))
		n += len(x.StringValue)
	case *StructuredValue_BoolValue:
		n += 1 // tag and wire
		n += 1
	case *StructuredValue_TensorShapeValue:
		s := proto.Size(x.TensorShapeValue)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StructuredValue_TensorDtypeValue:
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(x.TensorDtypeValue))
	case *StructuredValue_TensorSpecValue:
		s := proto.Size(x.TensorSpecValue)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StructuredValue_TypeSpecValue:
		s := proto.Size(x.TypeSpecValue)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StructuredValue_BoundedTensorSpecValue:
		s := proto.Size(x.BoundedTensorSpecValue)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StructuredValue_ListValue:
		s := proto.Size(x.ListValue)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StructuredValue_TupleValue:
		s := proto.Size(x.TupleValue)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StructuredValue_DictValue:
		s := proto.Size(x.DictValue)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StructuredValue_NamedTupleValue:
		s := proto.Size(x.NamedTupleValue)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Represents None.
type NoneValue struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoneValue) Reset()         { *m = NoneValue{} }
func (m *NoneValue) String() string { return proto.CompactTextString(m) }
func (*NoneValue) ProtoMessage()    {}
func (*NoneValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_struct_b79935a3b64f0a23, []int{1}
}
func (m *NoneValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoneValue.Unmarshal(m, b)
}
func (m *NoneValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoneValue.Marshal(b, m, deterministic)
}
func (dst *NoneValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoneValue.Merge(dst, src)
}
func (m *NoneValue) XXX_Size() int {
	return xxx_messageInfo_NoneValue.Size(m)
}
func (m *NoneValue) XXX_DiscardUnknown() {
	xxx_messageInfo_NoneValue.DiscardUnknown(m)
}

var xxx_messageInfo_NoneValue proto.InternalMessageInfo

// Represents a Python list.
type ListValue struct {
	Values               []*StructuredValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListValue) Reset()         { *m = ListValue{} }
func (m *ListValue) String() string { return proto.CompactTextString(m) }
func (*ListValue) ProtoMessage()    {}
func (*ListValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_struct_b79935a3b64f0a23, []int{2}
}
func (m *ListValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListValue.Unmarshal(m, b)
}
func (m *ListValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListValue.Marshal(b, m, deterministic)
}
func (dst *ListValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListValue.Merge(dst, src)
}
func (m *ListValue) XXX_Size() int {
	return xxx_messageInfo_ListValue.Size(m)
}
func (m *ListValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ListValue.DiscardUnknown(m)
}

var xxx_messageInfo_ListValue proto.InternalMessageInfo

func (m *ListValue) GetValues() []*StructuredValue {
	if m != nil {
		return m.Values
	}
	return nil
}

// Represents a Python tuple.
type TupleValue struct {
	Values               []*StructuredValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TupleValue) Reset()         { *m = TupleValue{} }
func (m *TupleValue) String() string { return proto.CompactTextString(m) }
func (*TupleValue) ProtoMessage()    {}
func (*TupleValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_struct_b79935a3b64f0a23, []int{3}
}
func (m *TupleValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TupleValue.Unmarshal(m, b)
}
func (m *TupleValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TupleValue.Marshal(b, m, deterministic)
}
func (dst *TupleValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TupleValue.Merge(dst, src)
}
func (m *TupleValue) XXX_Size() int {
	return xxx_messageInfo_TupleValue.Size(m)
}
func (m *TupleValue) XXX_DiscardUnknown() {
	xxx_messageInfo_TupleValue.DiscardUnknown(m)
}

var xxx_messageInfo_TupleValue proto.InternalMessageInfo

func (m *TupleValue) GetValues() []*StructuredValue {
	if m != nil {
		return m.Values
	}
	return nil
}

// Represents a Python dict keyed by `str`.
// The comment on Unicode from Value.string_value applies analogously.
type DictValue struct {
	Fields               map[string]*StructuredValue `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *DictValue) Reset()         { *m = DictValue{} }
func (m *DictValue) String() string { return proto.CompactTextString(m) }
func (*DictValue) ProtoMessage()    {}
func (*DictValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_struct_b79935a3b64f0a23, []int{4}
}
func (m *DictValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DictValue.Unmarshal(m, b)
}
func (m *DictValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DictValue.Marshal(b, m, deterministic)
}
func (dst *DictValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DictValue.Merge(dst, src)
}
func (m *DictValue) XXX_Size() int {
	return xxx_messageInfo_DictValue.Size(m)
}
func (m *DictValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DictValue.DiscardUnknown(m)
}

var xxx_messageInfo_DictValue proto.InternalMessageInfo

func (m *DictValue) GetFields() map[string]*StructuredValue {
	if m != nil {
		return m.Fields
	}
	return nil
}

// Represents a (key, value) pair.
type PairValue struct {
	Key                  string           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *StructuredValue `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PairValue) Reset()         { *m = PairValue{} }
func (m *PairValue) String() string { return proto.CompactTextString(m) }
func (*PairValue) ProtoMessage()    {}
func (*PairValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_struct_b79935a3b64f0a23, []int{5}
}
func (m *PairValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PairValue.Unmarshal(m, b)
}
func (m *PairValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PairValue.Marshal(b, m, deterministic)
}
func (dst *PairValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairValue.Merge(dst, src)
}
func (m *PairValue) XXX_Size() int {
	return xxx_messageInfo_PairValue.Size(m)
}
func (m *PairValue) XXX_DiscardUnknown() {
	xxx_messageInfo_PairValue.DiscardUnknown(m)
}

var xxx_messageInfo_PairValue proto.InternalMessageInfo

func (m *PairValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PairValue) GetValue() *StructuredValue {
	if m != nil {
		return m.Value
	}
	return nil
}

// Represents Python's namedtuple.
type NamedTupleValue struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values               []*PairValue `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NamedTupleValue) Reset()         { *m = NamedTupleValue{} }
func (m *NamedTupleValue) String() string { return proto.CompactTextString(m) }
func (*NamedTupleValue) ProtoMessage()    {}
func (*NamedTupleValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_struct_b79935a3b64f0a23, []int{6}
}
func (m *NamedTupleValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedTupleValue.Unmarshal(m, b)
}
func (m *NamedTupleValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedTupleValue.Marshal(b, m, deterministic)
}
func (dst *NamedTupleValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedTupleValue.Merge(dst, src)
}
func (m *NamedTupleValue) XXX_Size() int {
	return xxx_messageInfo_NamedTupleValue.Size(m)
}
func (m *NamedTupleValue) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedTupleValue.DiscardUnknown(m)
}

var xxx_messageInfo_NamedTupleValue proto.InternalMessageInfo

func (m *NamedTupleValue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NamedTupleValue) GetValues() []*PairValue {
	if m != nil {
		return m.Values
	}
	return nil
}

// A protobuf to represent tf.TensorSpec.
type TensorSpecProto struct {
	Name                 string                                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shape                *tensor_shape_go_proto.TensorShapeProto `protobuf:"bytes,2,opt,name=shape,proto3" json:"shape,omitempty"`
	Dtype                types_go_proto.DataType                 `protobuf:"varint,3,opt,name=dtype,proto3,enum=tensorflow.DataType" json:"dtype,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *TensorSpecProto) Reset()         { *m = TensorSpecProto{} }
func (m *TensorSpecProto) String() string { return proto.CompactTextString(m) }
func (*TensorSpecProto) ProtoMessage()    {}
func (*TensorSpecProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_struct_b79935a3b64f0a23, []int{7}
}
func (m *TensorSpecProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TensorSpecProto.Unmarshal(m, b)
}
func (m *TensorSpecProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TensorSpecProto.Marshal(b, m, deterministic)
}
func (dst *TensorSpecProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TensorSpecProto.Merge(dst, src)
}
func (m *TensorSpecProto) XXX_Size() int {
	return xxx_messageInfo_TensorSpecProto.Size(m)
}
func (m *TensorSpecProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TensorSpecProto.DiscardUnknown(m)
}

var xxx_messageInfo_TensorSpecProto proto.InternalMessageInfo

func (m *TensorSpecProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TensorSpecProto) GetShape() *tensor_shape_go_proto.TensorShapeProto {
	if m != nil {
		return m.Shape
	}
	return nil
}

func (m *TensorSpecProto) GetDtype() types_go_proto.DataType {
	if m != nil {
		return m.Dtype
	}
	return types_go_proto.DataType_DT_INVALID
}

// A protobuf to represent tf.BoundedTensorSpec.
type BoundedTensorSpecProto struct {
	Name                 string                                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shape                *tensor_shape_go_proto.TensorShapeProto `protobuf:"bytes,2,opt,name=shape,proto3" json:"shape,omitempty"`
	Dtype                types_go_proto.DataType                 `protobuf:"varint,3,opt,name=dtype,proto3,enum=tensorflow.DataType" json:"dtype,omitempty"`
	Minimum              *tensor_go_proto.TensorProto            `protobuf:"bytes,4,opt,name=minimum,proto3" json:"minimum,omitempty"`
	Maximum              *tensor_go_proto.TensorProto            `protobuf:"bytes,5,opt,name=maximum,proto3" json:"maximum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *BoundedTensorSpecProto) Reset()         { *m = BoundedTensorSpecProto{} }
func (m *BoundedTensorSpecProto) String() string { return proto.CompactTextString(m) }
func (*BoundedTensorSpecProto) ProtoMessage()    {}
func (*BoundedTensorSpecProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_struct_b79935a3b64f0a23, []int{8}
}
func (m *BoundedTensorSpecProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoundedTensorSpecProto.Unmarshal(m, b)
}
func (m *BoundedTensorSpecProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoundedTensorSpecProto.Marshal(b, m, deterministic)
}
func (dst *BoundedTensorSpecProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoundedTensorSpecProto.Merge(dst, src)
}
func (m *BoundedTensorSpecProto) XXX_Size() int {
	return xxx_messageInfo_BoundedTensorSpecProto.Size(m)
}
func (m *BoundedTensorSpecProto) XXX_DiscardUnknown() {
	xxx_messageInfo_BoundedTensorSpecProto.DiscardUnknown(m)
}

var xxx_messageInfo_BoundedTensorSpecProto proto.InternalMessageInfo

func (m *BoundedTensorSpecProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BoundedTensorSpecProto) GetShape() *tensor_shape_go_proto.TensorShapeProto {
	if m != nil {
		return m.Shape
	}
	return nil
}

func (m *BoundedTensorSpecProto) GetDtype() types_go_proto.DataType {
	if m != nil {
		return m.Dtype
	}
	return types_go_proto.DataType_DT_INVALID
}

func (m *BoundedTensorSpecProto) GetMinimum() *tensor_go_proto.TensorProto {
	if m != nil {
		return m.Minimum
	}
	return nil
}

func (m *BoundedTensorSpecProto) GetMaximum() *tensor_go_proto.TensorProto {
	if m != nil {
		return m.Maximum
	}
	return nil
}

// Represents a tf.TypeSpec
type TypeSpecProto struct {
	TypeSpecClass TypeSpecProto_TypeSpecClass `protobuf:"varint,1,opt,name=type_spec_class,json=typeSpecClass,proto3,enum=tensorflow.TypeSpecProto_TypeSpecClass" json:"type_spec_class,omitempty"`
	// The value returned by TypeSpec._serialize().
	TypeState *StructuredValue `protobuf:"bytes,2,opt,name=type_state,json=typeState,proto3" json:"type_state,omitempty"`
	// This is currently redundant with the type_spec_class enum, and is only
	// used for error reporting.  In particular, if you use an older binary to
	// load a newer model, and the model uses a TypeSpecClass that the older
	// binary doesn't support, then this lets us display a useful error message.
	TypeSpecClassName    string   `protobuf:"bytes,3,opt,name=type_spec_class_name,json=typeSpecClassName,proto3" json:"type_spec_class_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeSpecProto) Reset()         { *m = TypeSpecProto{} }
func (m *TypeSpecProto) String() string { return proto.CompactTextString(m) }
func (*TypeSpecProto) ProtoMessage()    {}
func (*TypeSpecProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_struct_b79935a3b64f0a23, []int{9}
}
func (m *TypeSpecProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeSpecProto.Unmarshal(m, b)
}
func (m *TypeSpecProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeSpecProto.Marshal(b, m, deterministic)
}
func (dst *TypeSpecProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeSpecProto.Merge(dst, src)
}
func (m *TypeSpecProto) XXX_Size() int {
	return xxx_messageInfo_TypeSpecProto.Size(m)
}
func (m *TypeSpecProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeSpecProto.DiscardUnknown(m)
}

var xxx_messageInfo_TypeSpecProto proto.InternalMessageInfo

func (m *TypeSpecProto) GetTypeSpecClass() TypeSpecProto_TypeSpecClass {
	if m != nil {
		return m.TypeSpecClass
	}
	return TypeSpecProto_UNKNOWN
}

func (m *TypeSpecProto) GetTypeState() *StructuredValue {
	if m != nil {
		return m.TypeState
	}
	return nil
}

func (m *TypeSpecProto) GetTypeSpecClassName() string {
	if m != nil {
		return m.TypeSpecClassName
	}
	return ""
}

func init() {
	proto.RegisterType((*StructuredValue)(nil), "tensorflow.StructuredValue")
	proto.RegisterType((*NoneValue)(nil), "tensorflow.NoneValue")
	proto.RegisterType((*ListValue)(nil), "tensorflow.ListValue")
	proto.RegisterType((*TupleValue)(nil), "tensorflow.TupleValue")
	proto.RegisterType((*DictValue)(nil), "tensorflow.DictValue")
	proto.RegisterMapType((map[string]*StructuredValue)(nil), "tensorflow.DictValue.FieldsEntry")
	proto.RegisterType((*PairValue)(nil), "tensorflow.PairValue")
	proto.RegisterType((*NamedTupleValue)(nil), "tensorflow.NamedTupleValue")
	proto.RegisterType((*TensorSpecProto)(nil), "tensorflow.TensorSpecProto")
	proto.RegisterType((*BoundedTensorSpecProto)(nil), "tensorflow.BoundedTensorSpecProto")
	proto.RegisterType((*TypeSpecProto)(nil), "tensorflow.TypeSpecProto")
	proto.RegisterEnum("tensorflow.TypeSpecProto_TypeSpecClass", TypeSpecProto_TypeSpecClass_name, TypeSpecProto_TypeSpecClass_value)
}

func init() {
	proto.RegisterFile("tensorflow/core/protobuf/struct.proto", fileDescriptor_struct_b79935a3b64f0a23)
}

var fileDescriptor_struct_b79935a3b64f0a23 = []byte{
	// 934 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xed, 0x6e, 0xe2, 0x46,
	0x14, 0xc5, 0x21, 0x90, 0xf5, 0x25, 0x04, 0x32, 0xcd, 0x66, 0xb3, 0x69, 0xa5, 0x25, 0x5e, 0xa5,
	0x45, 0x55, 0x0b, 0xda, 0x64, 0x1b, 0x75, 0xf7, 0x57, 0x1d, 0x70, 0x17, 0x5a, 0x04, 0xd6, 0xd8,
	0xcd, 0xb6, 0xfd, 0x63, 0x19, 0x18, 0xb2, 0x56, 0x8c, 0x8d, 0xec, 0xa1, 0x5b, 0x1e, 0xa0, 0xaf,
	0xd1, 0x57, 0xea, 0x0b, 0xf4, 0x29, 0xfa, 0x02, 0xad, 0x66, 0xc6, 0x5f, 0x18, 0x76, 0x53, 0x55,
	0x95, 0xf6, 0x0f, 0xcc, 0x3d, 0x3e, 0xf7, 0xdc, 0x33, 0x77, 0xc6, 0x57, 0x86, 0x73, 0x4a, 0xbc,
	0xd0, 0x0f, 0x66, 0xae, 0xff, 0xb6, 0x3d, 0xf1, 0x03, 0xd2, 0x5e, 0x04, 0x3e, 0xf5, 0xc7, 0xcb,
	0x59, 0x3b, 0xa4, 0xc1, 0x72, 0x42, 0x5b, 0x3c, 0x46, 0x90, 0xd2, 0x4e, 0x3f, 0xcd, 0xa7, 0xcc,
	0x02, 0x7b, 0x4e, 0xde, 0xfa, 0xc1, 0x5d, 0x5b, 0x3c, 0x11, 0x39, 0xa7, 0x5f, 0xdc, 0xc7, 0xb3,
	0xc2, 0x37, 0xf6, 0x82, 0x44, 0xec, 0xf3, 0xf7, 0xb0, 0x57, 0x0b, 0x12, 0x0a, 0x9a, 0xf2, 0x67,
	0x19, 0x6a, 0x06, 0x77, 0xb6, 0x0c, 0xc8, 0xf4, 0xc6, 0x76, 0x97, 0x04, 0x5d, 0x01, 0x78, 0xbe,
	0x47, 0xac, 0x5f, 0x58, 0x74, 0x22, 0x35, 0xa4, 0x66, 0xe5, 0xe2, 0x61, 0x2b, 0xd5, 0x6b, 0x0d,
	0x7d, 0x8f, 0x70, 0x6a, 0xaf, 0x80, 0x65, 0x2f, 0x0e, 0xd0, 0x39, 0x54, 0x67, 0xae, 0x6f, 0xd3,
	0xab, 0xe7, 0x51, 0x6a, 0xa5, 0x21, 0x35, 0xa5, 0x5e, 0x01, 0xef, 0x47, 0xb0, 0xa0, 0x9d, 0x41,
	0xc5, 0xf1, 0x52, 0xd2, 0x7e, 0x43, 0x6a, 0xa2, 0x5e, 0x01, 0x03, 0x07, 0x05, 0xe5, 0x29, 0xec,
	0x87, 0x34, 0x70, 0xbc, 0xdb, 0x88, 0x53, 0x6d, 0x48, 0x4d, 0xb9, 0x57, 0xc0, 0x15, 0x81, 0x0a,
	0xd2, 0x13, 0x80, 0xb1, 0xef, 0xbb, 0x11, 0xe5, 0xa0, 0x21, 0x35, 0x1f, 0x30, 0x3f, 0x0c, 0x13,
	0x84, 0x01, 0xa0, 0x6c, 0x63, 0x22, 0xe2, 0x13, 0xbe, 0x9f, 0x4f, 0xb2, 0xfb, 0x31, 0xf9, 0xd2,
	0x60, 0x24, 0x9d, 0x75, 0xa5, 0x57, 0xc0, 0x75, 0x9a, 0x62, 0x42, 0xad, 0x9b, 0xa8, 0x4d, 0x59,
	0x03, 0x23, 0xb5, 0x46, 0x43, 0x6a, 0x1e, 0x5c, 0x1c, 0x65, 0xd5, 0xba, 0x36, 0xb5, 0xcd, 0xd5,
	0x82, 0xa4, 0x2a, 0x5d, 0x96, 0x20, 0x54, 0xfa, 0x70, 0x18, 0x7b, 0x5a, 0x90, 0x49, 0x24, 0x72,
	0xc6, 0x2d, 0x7d, 0xbc, 0xc5, 0xd2, 0x82, 0x4c, 0x62, 0x47, 0x35, 0x9a, 0x40, 0x42, 0xaa, 0x03,
	0x35, 0x6e, 0x24, 0x23, 0xa4, 0x70, 0xa1, 0xc7, 0x6b, 0x42, 0xab, 0x05, 0xc9, 0xca, 0x54, 0x69,
	0x04, 0x08, 0x11, 0x0b, 0x1e, 0x8f, 0xfd, 0xa5, 0x37, 0x25, 0x53, 0x6b, 0xd3, 0xd7, 0x53, 0x2e,
	0xa7, 0x64, 0xe5, 0xae, 0x05, 0x79, 0xd3, 0xde, 0xf1, 0x38, 0xff, 0x24, 0xb9, 0x4c, 0xae, 0x13,
	0xd2, 0x48, 0xf1, 0x72, 0xf3, 0x32, 0x0d, 0x9c, 0x90, 0x26, 0x97, 0xc9, 0x8d, 0x03, 0xf4, 0x02,
	0x2a, 0x74, 0xb9, 0x70, 0xe3, 0x3e, 0x3f, 0xe7, 0x89, 0xc7, 0x6b, 0x3b, 0x63, 0x8f, 0xe3, 0x4c,
	0xa0, 0x49, 0xc4, 0x4a, 0x4e, 0x9d, 0x49, 0x5c, 0xf2, 0xab, 0xcd, 0x92, 0x5d, 0x67, 0x92, 0x96,
	0x9c, 0xc6, 0x01, 0x3b, 0x1b, 0xcf, 0x9e, 0xb3, 0x4e, 0x64, 0x0a, 0x5f, 0x6d, 0x9e, 0xcd, 0x90,
	0x91, 0xd6, 0xaa, 0xd7, 0xbc, 0x75, 0xe8, 0xba, 0x0c, 0xbb, 0x77, 0x8e, 0x37, 0x55, 0x2a, 0x20,
	0x27, 0x2f, 0x8b, 0xf2, 0x0d, 0xc8, 0xc9, 0x66, 0xd1, 0x25, 0x94, 0x79, 0x81, 0xf0, 0x44, 0x6a,
	0x14, 0xf3, 0x15, 0x72, 0x6f, 0x24, 0x8e, 0xa8, 0x8a, 0x0a, 0x90, 0x16, 0xf9, 0x6f, 0x12, 0xbf,
	0x4b, 0x20, 0x27, 0xfb, 0x47, 0x2f, 0xa0, 0x3c, 0x73, 0x88, 0x3b, 0x8d, 0x25, 0xce, 0xb6, 0xb6,
	0xa9, 0xf5, 0x2d, 0xe7, 0x68, 0x1e, 0x0d, 0x56, 0x38, 0x4a, 0x38, 0xbd, 0x81, 0x4a, 0x06, 0x46,
	0x75, 0x28, 0xde, 0x91, 0x15, 0x9f, 0x16, 0x32, 0x66, 0x4b, 0xf4, 0x0c, 0x4a, 0xa2, 0x85, 0x3b,
	0x9b, 0x2d, 0xcc, 0xbb, 0x13, 0xcc, 0x97, 0x3b, 0x5f, 0x4b, 0x8a, 0x0e, 0xb2, 0x6e, 0x3b, 0x81,
	0xf0, 0xf7, 0x7f, 0xa8, 0x2a, 0x26, 0xd4, 0x72, 0x47, 0x86, 0x10, 0xec, 0xb2, 0x23, 0x8b, 0x84,
	0xf9, 0x1a, 0x7d, 0x99, 0xb4, 0x73, 0x87, 0xf7, 0x62, 0xed, 0xca, 0x24, 0x96, 0x92, 0x46, 0xfe,
	0x26, 0x41, 0x2d, 0xf7, 0x1a, 0x6c, 0x95, 0xbd, 0x80, 0x12, 0x1f, 0x3f, 0x91, 0xe1, 0xf7, 0x0e,
	0x1e, 0x2c, 0xa8, 0xe8, 0x73, 0x28, 0xf1, 0x21, 0x73, 0x52, 0x7c, 0xf7, 0x78, 0xc1, 0x82, 0xa2,
	0xfc, 0x25, 0xc1, 0xf1, 0xf6, 0xb7, 0xf2, 0x43, 0xd8, 0x41, 0xcf, 0x60, 0x6f, 0xee, 0x78, 0xce,
	0x7c, 0x39, 0x3f, 0xd9, 0xe5, 0x15, 0x1e, 0x6d, 0x56, 0x10, 0xe2, 0x31, 0x8f, 0xa7, 0xd8, 0xbf,
	0xf2, 0x94, 0xd2, 0x7d, 0x29, 0x82, 0xa7, 0xfc, 0x51, 0x84, 0xea, 0xda, 0x64, 0x43, 0xa3, 0xec,
	0x34, 0x9c, 0xb8, 0x76, 0x18, 0xf2, 0x6d, 0x1f, 0x5c, 0x7c, 0xf6, 0xce, 0x69, 0x98, 0x44, 0x1d,
	0x46, 0x4f, 0x27, 0x23, 0x0f, 0xd1, 0x4b, 0x00, 0x21, 0x48, 0x6d, 0xfa, 0xaf, 0x6e, 0x9b, 0xcc,
	0xf3, 0x19, 0x1b, 0xb5, 0xe1, 0x28, 0x67, 0xc6, 0xe2, 0x07, 0x51, 0xe4, 0x07, 0x71, 0xb8, 0x56,
	0x88, 0x5d, 0x4d, 0xe5, 0x6f, 0x29, 0xdd, 0x8f, 0x28, 0x5f, 0x81, 0xbd, 0x1f, 0x86, 0xdf, 0x0f,
	0x47, 0xaf, 0x87, 0xf5, 0x02, 0x3a, 0x06, 0x64, 0xe8, 0x2a, 0x36, 0x34, 0xcb, 0xd4, 0x86, 0xc6,
	0x08, 0x5b, 0x86, 0xae, 0x75, 0xea, 0x12, 0x7a, 0x04, 0x1f, 0xf5, 0x87, 0x5d, 0xed, 0x47, 0xad,
	0x6b, 0x19, 0x83, 0x7e, 0x47, 0x33, 0xc4, 0x83, 0x1d, 0x96, 0x80, 0xd5, 0x57, 0xaf, 0xb4, 0xee,
	0x5a, 0x42, 0x11, 0x3d, 0x84, 0xc3, 0x08, 0x50, 0x31, 0x56, 0x7f, 0x12, 0xf0, 0x2e, 0x83, 0xbb,
	0xaa, 0xa9, 0x5a, 0xec, 0xc7, 0xd0, 0x4c, 0x01, 0x97, 0x98, 0x0a, 0x87, 0xfb, 0xa6, 0x86, 0x55,
	0x33, 0x56, 0x29, 0xa3, 0x43, 0xa8, 0x8e, 0x74, 0xb3, 0x3f, 0x1a, 0xaa, 0x03, 0x01, 0xed, 0xa1,
	0x23, 0xa8, 0xeb, 0x1a, 0xb6, 0xb0, 0xa6, 0x0f, 0xfa, 0x1d, 0x55, 0xa0, 0x0f, 0x18, 0xf1, 0x46,
	0xc5, 0x7d, 0xf5, 0x7a, 0xa0, 0x09, 0x48, 0xe6, 0xce, 0x46, 0xaf, 0x2d, 0x5d, 0xc5, 0x66, 0x9f,
	0x49, 0x08, 0x1c, 0xae, 0xbf, 0xfb, 0xb9, 0x77, 0xeb, 0xd0, 0x37, 0xcb, 0x71, 0x6b, 0xe2, 0xcf,
	0xdb, 0x99, 0x8f, 0x97, 0xed, 0xcb, 0x5b, 0x5f, 0x7c, 0xd5, 0xb0, 0x1f, 0x8b, 0x7f, 0xca, 0x84,
	0xd6, 0xad, 0x2f, 0x56, 0xe3, 0x32, 0xff, 0xbb, 0xfc, 0x27, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x43,
	0x7d, 0xc2, 0x8d, 0x09, 0x00, 0x00,
}
